-- Legal Setu — Supabase schema scaffold.
--
-- This is a placeholder. No tables are created yet; the actual schema
-- (users, chat_sessions, messages, agent_logs, case_history, documents,
-- etc.) will be designed once the orchestrator and agent contracts are
-- finalized.
--
-- Suggested areas to cover when this is filled in:
--   - auth/profile linkage (Supabase Auth users -> app profile table)
--   - chat sessions + messages (per agent, with routing metadata)
--   - case history / saved matters
--   - generated documents / uploaded files (with storage bucket refs)
--   - RAG source citations (Indian Constitution + verified legal sources)
--
-- example (commented out, not applied):
--
-- create table if not exists public.profiles (
--   id uuid primary key references auth.users (id) on delete cascade,
--   full_name text,
--   created_at timestamptz not null default now()
-- );
