import { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { useAuth } from './AuthContext.jsx';

const AppContext = createContext(null);

// English + all languages listed in the Eighth Schedule of the Constitution of India.
// `label` is the language's own native name (not an English translation of it).
export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'mr', label: 'मराठी' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'ur', label: 'اردو' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'or', label: 'ଓଡ଼ିଆ' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'as', label: 'অসমীয়া' },
  { code: 'mai', label: 'मैथिली' },
  { code: 'sa', label: 'संस्कृतम्' },
  { code: 'ks', label: 'कॉशुर' },
  { code: 'ne', label: 'नेपाली' },
  { code: 'kok', label: 'कोंकणी' },
  { code: 'sd', label: 'سنڌي' },
  { code: 'doi', label: 'डोगरी' },
  { code: 'mni', label: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { code: 'sat', label: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'brx', label: 'बड़ो' },
];

// Site-wide UI copy, keyed by dot-path (e.g. "chat.heading"). t() falls back
// to English for any key missing in the active language, so partial
// coverage degrades gracefully instead of breaking.
//
// The 8 languages below (en/hi/mr/bn/ta/te/kn/gu) have full site coverage:
// core strings (nav.newChat, chat.heading/subheading/placeholder) are in
// native script, translated by a previous PR; everything else here is a
// romanized (Latin-script) demo translation, not proofread by a native
// speaker. The remaining 14 Eighth Schedule languages only have those core
// native-script strings -- everything else falls back to English.
// Legal document pages (Privacy Policy, Terms of Service) and the agent
// descriptions in data/agents.js are intentionally left in English:
// mistranslated legal text is worse than none.
const STRINGS = {
  en: {
    nav: { newChat: 'New Chat', history: 'History' },
    chat: {
      heading: 'How can I help with your legal question today?',
      subheading: 'Ask in plain language, in the language you are most comfortable with.',
      placeholder: 'Describe your legal problem...',
      suggestion1: 'Review a contract',
      suggestion2: 'Know my tenant rights',
      suggestion3: 'Draft a legal notice',
      suggestionText1: 'Can you review my rental contract before I sign it?',
      suggestionText2: 'My landlord is refusing to return my security deposit.',
      suggestionText3: 'I need to draft a legal notice to my landlord about my security deposit.',
      approvedSuffix: 'approved by user',
      approvedBody: 'User approved the recommended specialist. Preparing a contextual handoff...',
      deniedTitle: 'Agent request denied',
      tryDifferent: 'Try a different specialist',
      responseReadySuffix: 'response ready',
      handoffBody: 'Your specialist has prepared a response based on the context shared during handoff.',
      errorBody: "We couldn't complete that step. Please try again.",
      tryAgain: 'Try Again',
      inputHint: 'Enter to send · Shift + Enter for a new line',
    },
    history: {
      title: 'Conversation History',
      subtitle: 'Revisit past conversations with the Legal Orchestrator.',
      empty: 'No conversation history yet.',
      conversation: 'Conversation',
      staticDemo: 'This is a static demo view — reopen a full session from the primary chat experience.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Manage your appearance, language, and conversation data.',
      appearance: 'Appearance',
      appearanceDesc: 'Choose how Legal Setu looks on your device.',
      theme: 'Theme',
      themeDesc: 'Light or dark mode, synced across the app.',
      light: 'Light',
      dark: 'Dark',
      language: 'Language',
      languageNote: 'Interface text is translated across the whole site for this demo.',
      interfaceLanguage: 'Interface language',
      profile: 'Profile',
      displayName: 'Display name',
      conversation: 'Conversation',
      clearHistory: 'Clear history',
      clearedMsg: 'Conversation history has been cleared.',
      clearDesc: 'Remove all saved conversations.',
      privacy: 'Privacy',
      shareData: 'Share anonymized data to improve responses',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Analyzing your query…',
      step1: 'Understanding the situation',
      step2: 'Identifying legal domain',
      step3: 'Selecting relevant expertise',
    },
    domain: {
      identifiedPrefix: 'Domain identified:',
      detected: 'Detected domain',
      topic: 'Topic',
      intent: 'User intent',
    },
    recommendation: { title: 'Recommended Agent', reason: 'Reason' },
    handoff: {
      handingOff: 'Handing off',
      preparing: 'Preparing contextual handoff…',
      contextExtracted: 'Context extracted',
      targetAgent: 'Target agent',
      working: 'Working',
      ready: 'Ready',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu provides AI-assisted legal information and does not replace professional legal advice.',
    },
    approval: { allow: 'Allow', deny: 'Deny' },
    home: {
      title: 'Legal Setu',
      desc: 'Ask your legal question in plain language. The Legal Orchestrator identifies the right domain and recommends a specialist agent — you decide whether to bring them in.',
      start: 'Start a conversation',
    },
    profile: {
      title: 'Profile',
      desc: 'Your account details on Legal Setu.',
      account: 'Account',
      fullName: 'Full name',
      email: 'Email',
      signedInVia: 'Signed in via',
      memberSince: 'Member since',
    },
    login: {
      welcome: 'Welcome to Legal Setu',
      desc: 'Sign in to get personalized legal guidance, with your conversation history and context saved to your account.',
      magicSentPrefix: 'Magic link sent to',
      magicSentSuffix: '. Check your inbox and click it to sign in.',
      redirecting: 'Redirecting to Google…',
      continueGoogle: 'Continue with Google',
      or: 'or',
      emailPlaceholder: 'you@example.com',
      sending: 'Sending link…',
      sendLink: 'Send magic link',
      terms: 'By continuing you agree this is a hackathon prototype, not a substitute for professional legal advice.',
    },
  },
  hi: {
    nav: { newChat: 'नई बातचीत', history: 'Itihaas' },
    chat: {
      heading: 'आज मैं आपके कानूनी प्रश्न में कैसे मदद कर सकता हूँ?',
      subheading: 'सरल भाषा में, अपनी पसंदीदा भाषा में पूछें।',
      placeholder: 'अपनी कानूनी समस्या बताएं...',
      suggestion1: 'Ek contract review karein',
      suggestion2: 'Apne kirayedaar adhikaar jaanein',
      suggestion3: 'Kanooni notice draft karein',
      suggestionText1: 'Kya aap sign karne se pehle mera rent contract check kar sakte hain?',
      suggestionText2: 'Mera makan-maalik security deposit vaapas nahi de raha hai.',
      suggestionText3: 'Mujhe security deposit ke baare mein makan-maalik ko kanooni notice bhejna hai.',
      approvedSuffix: 'user dwara manzoor',
      approvedBody: 'User ne suggest kiye gaye specialist ko manzoor kiya. Contextual handoff taiyaar ho raha hai...',
      deniedTitle: 'Agent request reject kiya gaya',
      tryDifferent: 'Doosra specialist try karein',
      responseReadySuffix: 'jawab taiyaar hai',
      handoffBody: 'Aapke specialist ne handoff ke dauraan share kiye gaye context ke aadhar par jawab taiyaar kiya hai.',
      errorBody: 'Yeh step poora nahi ho paaya. Kripya dobara try karein.',
      tryAgain: 'Dobara Try Karein',
      inputHint: 'Bhejne ke liye Enter · Nayi line ke liye Shift + Enter',
    },
    history: {
      title: 'Baatcheet ka Itihaas',
      subtitle: 'Legal Orchestrator ke saath purani baatcheet dekhein.',
      empty: 'Abhi tak koi baatcheet ka itihaas nahi hai.',
      conversation: 'Baatcheet',
      staticDemo: 'Yeh ek static demo view hai — poora session shuru karne ke liye main chat par jaayein.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Apna appearance, bhasha, aur baatcheet ka data manage karein.',
      appearance: 'Dikhawat',
      appearanceDesc: 'Legal Setu apne device par kaisa dikhe, chunein.',
      theme: 'Theme',
      themeDesc: 'Light ya dark mode, poore app mein sync hota hai.',
      light: 'Light',
      dark: 'Dark',
      language: 'Bhasha',
      languageNote: 'Is demo ke liye poori site ka text translate kiya gaya hai.',
      interfaceLanguage: 'Interface bhasha',
      profile: 'Profile',
      displayName: 'Display naam',
      conversation: 'Baatcheet',
      clearHistory: 'Itihaas saaf karein',
      clearedMsg: 'Baatcheet ka itihaas saaf kar diya gaya hai.',
      clearDesc: 'Saari saved baatcheet hataayein.',
      privacy: 'Privacy',
      shareData: 'Jawab behtar banane ke liye anonymized data share karein',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Aapka sawaal analyze ho raha hai…',
      step1: 'Sthiti ko samajhna',
      step2: 'Kanooni domain pehchaanna',
      step3: 'Sambandhit expertise chunna',
    },
    domain: {
      identifiedPrefix: 'Domain pehchaana gaya:',
      detected: 'Pehchaana gaya domain',
      topic: 'Topic',
      intent: 'User ka intent',
    },
    recommendation: { title: 'Suggest kiya gaya Agent', reason: 'Kaaran' },
    handoff: {
      handingOff: 'Handoff ho raha hai',
      preparing: 'Contextual handoff taiyaar ho raha hai…',
      contextExtracted: 'Context nikaala gaya',
      targetAgent: 'Target agent',
      working: 'Kaam ho raha hai',
      ready: 'Taiyaar',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-assisted kanooni jaankaari deta hai aur professional kanooni salaah ka viklap nahi hai.',
    },
    approval: { allow: 'Manzoor', deny: 'Reject' },
    home: {
      title: 'Legal Setu',
      desc: 'Apna kanooni sawaal saral bhasha mein poochein. Legal Orchestrator sahi domain pehchaanta hai aur specialist agent suggest karta hai — unhe shaamil karna ya nahi, yeh aap tay karte hain.',
      start: 'Baatcheet shuru karein',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu par aapke account ki details.',
      account: 'Account',
      fullName: 'Poora naam',
      email: 'Email',
      signedInVia: 'Sign in kiya gaya',
      memberSince: 'Member kab se',
    },
    login: {
      welcome: 'Legal Setu mein aapka swagat hai',
      desc: 'Personalized kanooni guidance ke liye sign in karein, aapka baatcheet ka itihaas aur context aapke account mein saved rahega.',
      magicSentPrefix: 'Magic link bhej diya gaya',
      magicSentSuffix: '. Apna inbox check karein aur sign in karne ke liye click karein.',
      redirecting: 'Google par redirect ho raha hai…',
      continueGoogle: 'Google se continue karein',
      or: 'ya',
      emailPlaceholder: 'aap@example.com',
      sending: 'Link bhej rahe hain…',
      sendLink: 'Magic link bhejein',
      terms: 'Continue karke aap sehmat hain ki yeh ek hackathon prototype hai, professional kanooni salaah ka viklap nahi.',
    },
  },
  mr: {
    nav: { newChat: 'नवीन संभाषण', history: 'Itihaas' },
    chat: {
      heading: 'आज मी तुमच्या कायदेशीर प्रश्नात कशी मदत करू शकतो?',
      subheading: 'सोप्या भाषेत, तुम्हाला सोयीस्कर असलेल्या भाषेत विचारा.',
      placeholder: 'तुमची कायदेशीर समस्या सांगा...',
      suggestion1: 'Contract review kara',
      suggestion2: 'Bhadekaru hakk jaana',
      suggestion3: 'Kayadeshir notice draft kara',
      suggestionText1: 'Sahi karnyapurvi maza bhade karar tapasal ka?',
      suggestionText2: 'Maza gharmalak security deposit paratich denyas nakar det aahe.',
      suggestionText3: 'Malaa security depositbaddal gharmalakala kayadeshir notice pathvaycha aahe.',
      approvedSuffix: 'user dware manjur',
      approvedBody: 'User ne suchavlelya specialistla manjuri dili. Contextual handoff taiyaar hot aahe...',
      deniedTitle: 'Agent request naakarli',
      tryDifferent: 'Dusra specialist try kara',
      responseReadySuffix: 'uttar taiyaar aahe',
      handoffBody: 'Tumchya specialistne handoff dvaare milalelya context varun uttar taiyaar kele aahe.',
      errorBody: 'Ha step purna hou shakla nahi. Krupaya punha prayatna kara.',
      tryAgain: 'Punha Prayatna Kara',
      inputHint: 'Pathvayla Enter · Navin ol sathi Shift + Enter',
    },
    history: {
      title: 'Samvaad Itihaas',
      subtitle: 'Legal Orchestrator sobat julya samvaadanna bhet dya.',
      empty: 'Ajun koni samvaad itihaas nahi.',
      conversation: 'Samvaad',
      staticDemo: 'Ha ek static demo view aahe — purna session sathi main chat var jaa.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Tumche appearance, bhasha, aani samvaad data vyavasthit kara.',
      appearance: 'Deekhava',
      appearanceDesc: 'Legal Setu tumchya device var kasa disel te nivda.',
      theme: 'Theme',
      themeDesc: 'Light kinva dark mode, sampurna app madhe sync hoto.',
      light: 'Light',
      dark: 'Dark',
      language: 'Bhasha',
      languageNote: 'Ya demo sathi sampurna site cha text bhashantarit kela aahe.',
      interfaceLanguage: 'Interface bhasha',
      profile: 'Profile',
      displayName: 'Display naav',
      conversation: 'Samvaad',
      clearHistory: 'Itihaas saaf kara',
      clearedMsg: 'Samvaad itihaas saaf kela gela aahe.',
      clearDesc: 'Sarv saved samvaad kadha.',
      privacy: 'Privacy',
      shareData: 'Uttar sudharnyasathi anonymized data share kara',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Tumcha prashna analyze hot aahe…',
      step1: 'Paristhiti samjun ghene',
      step2: 'Kayadeshir domain olakhne',
      step3: 'Sambandhit tajnata nivadne',
    },
    domain: {
      identifiedPrefix: 'Domain olakhla gela:',
      detected: 'Olakhlela domain',
      topic: 'Topic',
      intent: 'User cha hetu',
    },
    recommendation: { title: 'Suchavlela Agent', reason: 'Karan' },
    handoff: {
      handingOff: 'Handoff hot aahe',
      preparing: 'Contextual handoff taiyaar hot aahe…',
      contextExtracted: 'Context kadhla',
      targetAgent: 'Target agent',
      working: 'Kaam sur aahe',
      ready: 'Taiyaar',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-sahayyit kayadeshir mahiti deto ani professional kayadeshir salla cha paryay nahi.',
    },
    approval: { allow: 'Manjur', deny: 'Naakar' },
    home: {
      title: 'Legal Setu',
      desc: 'Tumcha kayadeshir prashna sopya bhashet vichara. Legal Orchestrator yogya domain olakhto ani specialist agent suchavto — tyanna samaavesh karaycha ki nahi te tumhi tharvata.',
      start: 'Samvaad suru kara',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu var tumchya account chi details.',
      account: 'Account',
      fullName: 'Pura naav',
      email: 'Email',
      signedInVia: 'Sign in kele',
      memberSince: 'Member kadhi pasun',
    },
    login: {
      welcome: 'Legal Setu madhe tumche swagat aahe',
      desc: 'Personalized kayadeshir margdarshanasathi sign in kara, tumcha samvaad itihaas ani context tumchya account madhe saved rahil.',
      magicSentPrefix: 'Magic link pathavla',
      magicSentSuffix: '. Tumcha inbox tapasa ani sign in karnyasathi click kara.',
      redirecting: 'Google kade redirect hot aahe…',
      continueGoogle: 'Google sobat continue kara',
      or: 'kinva',
      emailPlaceholder: 'tumhi@example.com',
      sending: 'Link pathavat aahot…',
      sendLink: 'Magic link pathava',
      terms: 'Continue karun tumhi manya karta ki ha ek hackathon prototype aahe, professional kayadeshir sallyacha paryay nahi.',
    },
  },
  bn: {
    nav: { newChat: 'নতুন আলাপ', history: 'Itihash' },
    chat: {
      heading: 'আজ আমি আপনার আইনি প্রশ্নে কীভাবে সাহায্য করতে পারি?',
      subheading: 'সহজ ভাষায়, আপনার পছন্দের ভাষায় জিজ্ঞাসা করুন।',
      placeholder: 'আপনার আইনি সমস্যা বর্ণনা করুন...',
      suggestion1: 'Ekti chukti review korun',
      suggestion2: 'Bhara-tir adhikar janun',
      suggestion3: 'Aini notice draft korun',
      suggestionText1: 'Sign korar age ki amar bhara chukti dekhben?',
      suggestionText2: 'Amar barir malik security deposit ferot dite raji na.',
      suggestionText3: 'Amake security deposit niye barir malik ke aini notice pathate hobe.',
      approvedSuffix: 'user dara onumodito',
      approvedBody: 'User suggest kora specialist ke onumodon diyeche. Contextual handoff taiyar hocche...',
      deniedTitle: 'Agent request prottakhato holo',
      tryDifferent: 'Onno specialist try korun',
      responseReadySuffix: 'uttor taiyar',
      handoffBody: 'Apnar specialist handoff-e share kora context onujayi uttor taiyar korechen.',
      errorBody: 'Ei step shesh kora jayni. Doya kore abar cheshta korun.',
      tryAgain: 'Abar Cheshta Korun',
      inputHint: 'Pathate Enter · Notun line-er jonno Shift + Enter',
    },
    history: {
      title: 'Alaap Itihash',
      subtitle: 'Legal Orchestrator er sathe purono alaap dekhun.',
      empty: 'Ekhono kono alaaper itihash nei.',
      conversation: 'Alaap',
      staticDemo: 'Eta ekta static demo view — purno session-er jonno main chat-e jaan.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Apnar appearance, bhasha, ebong alaaper data poricholona korun.',
      appearance: 'Chehara',
      appearanceDesc: 'Apnar device-e Legal Setu kemon dekhabe beche nin.',
      theme: 'Theme',
      themeDesc: 'Light ba dark mode, shomosto app-e sync hoy.',
      light: 'Light',
      dark: 'Dark',
      language: 'Bhasha',
      languageNote: 'Ei demo-r jonno pura site-er text onubad kora hoyeche.',
      interfaceLanguage: 'Interface bhasha',
      profile: 'Profile',
      displayName: 'Display naam',
      conversation: 'Alaap',
      clearHistory: 'Itihash muche felun',
      clearedMsg: 'Alaaper itihash muche fela hoyeche.',
      clearDesc: 'Shob saved alaap shorao.',
      privacy: 'Privacy',
      shareData: 'Uttor bhalo korte anonymized data share korun',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Apnar proshno analyze hocche…',
      step1: 'Poristhiti bujhte pray',
      step2: 'Aini domain chinhito kora',
      step3: 'Prasongik expertise beche neya',
    },
    domain: {
      identifiedPrefix: 'Domain chinhito hoyeche:',
      detected: 'Chinhito domain',
      topic: 'Bishoy',
      intent: 'User-er uddesho',
    },
    recommendation: { title: 'Suggest kora Agent', reason: 'Karon' },
    handoff: {
      handingOff: 'Handoff hocche',
      preparing: 'Contextual handoff taiyar hocche…',
      contextExtracted: 'Context ber kora hoyeche',
      targetAgent: 'Target agent',
      working: 'Kaj cholche',
      ready: 'Taiyar',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-sahajyoprapto aini tottho pradan kore ebong professional aini poramorsher bikolpo noy.',
    },
    approval: { allow: 'Onumodon', deny: 'Prottakhan' },
    home: {
      title: 'Legal Setu',
      desc: 'Apnar aini proshno sohoj bhashay jiggasa korun. Legal Orchestrator shothik domain chinhito kore ebong ekjon specialist agent suggest kore — tader jorito korben kina apni thik korben.',
      start: 'Alaap shuru korun',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu-te apnar account-er details.',
      account: 'Account',
      fullName: 'Puro naam',
      email: 'Email',
      signedInVia: 'Sign in kora hoyeche',
      memberSince: 'Member kobe theke',
    },
    login: {
      welcome: 'Legal Setu-te apnake swagatom',
      desc: 'Personalized aini guidance-er jonno sign in korun, apnar alaaper itihash ebong context apnar account-e saved thakbe.',
      magicSentPrefix: 'Magic link pathano hoyeche',
      magicSentSuffix: '. Apnar inbox check korun ebong sign in korte click korun.',
      redirecting: 'Google-e redirect hocche…',
      continueGoogle: 'Google diye continue korun',
      or: 'ba',
      emailPlaceholder: 'apni@example.com',
      sending: 'Link pathano hocche…',
      sendLink: 'Magic link pathan',
      terms: 'Continue kore apni shommoto hocchen je eta ekta hackathon prototype, professional aini poramorsher bikolpo noy.',
    },
  },
  ta: {
    nav: { newChat: 'புதிய உரையாடல்', history: 'Varalaru' },
    chat: {
      heading: 'இன்று உங்கள் சட்டப் பிரச்சினைக்கு நான் எப்படி உதவ முடியும்?',
      subheading: 'எளிய மொழியில், நீங்கள் வசதியாக உணரும் மொழியில் கேளுங்கள்.',
      placeholder: 'உங்கள் சட்டப் பிரச்சினையை விவரிக்கவும்...',
      suggestion1: 'Or ozhungkumurai review seyyavum',
      suggestion2: 'En kudiyiruppu urimaigalai ariyavum',
      suggestion3: 'Sattak arivippu vadivamai',
      suggestionText1: 'Naan kaiyezhuthiduvatharku munpu en vaadagai ozhungkumuraiyai paarvaiyidungal?',
      suggestionText2: 'En veetu utaimaiyaalar paadhukappu vaipputhogaiyai thirumba tharamal irukiraar.',
      suggestionText3: 'Paadhukappu vaipputhogai patri veetu utaimaiyaalarukku sattak arivippu vadivamaikka vendum.',
      approvedSuffix: 'panipavaraal oppukondathu',
      approvedBody: 'Panipavar pariyntharaikkappatta nipunarai oppukondaar. Contextual handoff thayaraagirathu...',
      deniedTitle: 'Agent kettukkolgai niraakarikkapattathu',
      tryDifferent: 'Vera nipunar mudhalvu seyya',
      responseReadySuffix: 'pathil thayaar',
      handoffBody: 'Handoff-in podhu pakirappatta context adhaaramaaga ungal nipunar pathilai thayaar seithullaar.',
      errorBody: 'Andha padi mudikkap padavillai. Meendum muyalavum.',
      tryAgain: 'Meendum Muyalavum',
      inputHint: 'Anuppa Enter · Puthiya varikku Shift + Enter',
    },
    history: {
      title: 'Uraiyaadal Varalaru',
      subtitle: 'Legal Orchestrator udan munnaal uraiyaadalgalai meendum paarkavum.',
      empty: 'Innum uraiyaadal varalaru illai.',
      conversation: 'Uraiyaadal',
      staticDemo: 'Ithu oru nirandhara demo kaatchi — pooranamaana session-ukku pradhaana chat-ukku selavum.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Ungal thondru, mozhi, matrum uraiyaadal thagavalai nirvagikkavum.',
      appearance: 'Thondru',
      appearanceDesc: 'Ungal saadhanam-il Legal Setu eppadi theriyum enbadhai therivu seyyavum.',
      theme: 'Theme',
      themeDesc: 'Light alladhu dark mode, app muzhuvadhilum sync aagum.',
      light: 'Light',
      dark: 'Dark',
      language: 'Mozhi',
      languageNote: 'Indha demo-vukku muzhu site-in text-um mozhipeyarkkapattullathu.',
      interfaceLanguage: 'Interface mozhi',
      profile: 'Profile',
      displayName: 'Display peyar',
      conversation: 'Uraiyaadal',
      clearHistory: 'Varalaru azhi',
      clearDesc: 'Anaithu saved uraiyaadalgalaium neekavum.',
      clearedMsg: 'Uraiyaadal varalaru azhikkappattadhu.',
      privacy: 'Privacy',
      shareData: 'Pathilgalai mecchapaduthha anonymized data pagirvum',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Ungal kelvi aaraaycchi seyyapadugirathu…',
      step1: 'Nilaimai purinthu kolgirathu',
      step2: 'Sattak thurai kandarigirathu',
      step3: 'Poruthamaana nipunathuvathai therndhedukkirathu',
    },
    domain: {
      identifiedPrefix: 'Thurai kandarikkapattathu:',
      detected: 'Kandarikkapatta thurai',
      topic: 'Thalaippu',
      intent: 'Panipavarin nokkam',
    },
    recommendation: { title: 'Pariyndhurikkapatta Agent', reason: 'Kaaranam' },
    handoff: {
      handingOff: 'Handoff seyyapadugirathu',
      preparing: 'Contextual handoff thayaraagirathu…',
      contextExtracted: 'Context eduthukollapattathu',
      targetAgent: 'Ilakku agent',
      working: 'Velai nadakkirathu',
      ready: 'Thayaar',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-udaviyudan sattak thagavalai vazhangugirathu, ithu thozhilmurai satta aalosanaikku maatraaga illai.',
    },
    approval: { allow: 'Anumathi', deny: 'Niraakarikka' },
    home: {
      title: 'Legal Setu',
      desc: 'Ungal sattak kelviyai elimaiyaana mozhiyil kelungal. Legal Orchestrator sariyaana thuraiyai kandarithu oru nipunar agent-ai pariyndhuraikkum — avargalai serppadha endru neengal mudivu seiyalaam.',
      start: 'Uraiyaadalai thodangavum',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu-in ungal kanakku vivaramgal.',
      account: 'Kanakku',
      fullName: 'Muzhu peyar',
      email: 'Email',
      signedInVia: 'Sign in seyyapattathu',
      memberSince: 'Member aanadhu',
    },
    login: {
      welcome: 'Legal Setu-ku varaverkirom',
      desc: 'Thanippaduthapatta sattak vazhikaattudhalukku sign in seyyavum, ungal uraiyaadal varalaru matrum context ungal kanakkil saved seyyapadum.',
      magicSentPrefix: 'Magic link anuppapattadhu',
      magicSentSuffix: '. Ungal inbox-ai paarthu sign in seyya click seyyavum.',
      redirecting: 'Google-ukku redirect seyyapadugirathu…',
      continueGoogle: 'Google-udan continue seyyavum',
      or: 'allathu',
      emailPlaceholder: 'neenga@example.com',
      sending: 'Link anuppapadugirathu…',
      sendLink: 'Magic link anuppavum',
      terms: 'Continue seivadhaal ithu oru hackathon prototype endrum, thozhilmurai sattak aalosanaikku maatraaga illai endrum oppukolgireergal.',
    },
  },
  te: {
    nav: { newChat: 'కొత్త చాట్', history: 'Charitra' },
    chat: {
      heading: 'ఈ రోజు మీ న్యాయపరమైన ప్రశ్నకు నేను ఎలా సహాయం చేయగలను?',
      subheading: 'సరళమైన భాషలో, మీకు అనుకూలమైన భాషలో అడగండి.',
      placeholder: 'మీ న్యాయ సమస్యను వివరించండి...',
      suggestion1: 'Ottu review cheyandi',
      suggestion2: 'Naa bhadaka hakkulu telusukondi',
      suggestion3: 'Chatta notice draft cheyandi',
      suggestionText1: 'Sign cheyakamunde naa rental ottunu review cheyagalara?',
      suggestionText2: 'Naa illu yajamani security deposit thirigi ivvadaniki nirakaristhunnaru.',
      suggestionText3: 'Security deposit gurinchi illu yajamaniki chatta notice draft cheyali.',
      approvedSuffix: 'user dwara approve chesaru',
      approvedBody: 'User suchinchina specialist ni approve chesaru. Contextual handoff siddham avutundi...',
      deniedTitle: 'Agent request tiraskarincharu',
      tryDifferent: 'Vere specialist try cheyandi',
      responseReadySuffix: 'jawabu siddhamga undi',
      handoffBody: 'Mee specialist handoff samayamlo share chesina context aadharamga jawabu siddham chesaru.',
      errorBody: 'Aa step complete kaledu. Dayachesi malli try cheyandi.',
      tryAgain: 'Malli Try Cheyandi',
      inputHint: 'Pampadaniki Enter · Kotha line kosam Shift + Enter',
    },
    history: {
      title: 'Chat Charitra',
      subtitle: 'Legal Orchestrator to past chats ni malli chudandi.',
      empty: 'Inka e chat charitra ledu.',
      conversation: 'Chat',
      staticDemo: 'Idi oka static demo view — poorthi session kosam main chat ki vellandi.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Mee appearance, bhasha, mariyu chat data ni manage cheyandi.',
      appearance: 'Appearance',
      appearanceDesc: 'Legal Setu mee device lo ela kanipistundo enchukondi.',
      theme: 'Theme',
      themeDesc: 'Light leda dark mode, entire app lo sync avutundi.',
      light: 'Light',
      dark: 'Dark',
      language: 'Bhasha',
      languageNote: 'Ee demo kosam entire site text anuvadam chesaru.',
      interfaceLanguage: 'Interface bhasha',
      profile: 'Profile',
      displayName: 'Display peru',
      conversation: 'Chat',
      clearHistory: 'Charitra clear cheyandi',
      clearedMsg: 'Chat charitra clear chesaru.',
      clearDesc: 'Anni saved chats ni theeyandi.',
      privacy: 'Privacy',
      shareData: 'Samadhanalanu merugu parachadaniki anonymized data share cheyandi',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Mee prashna analyze avutundi…',
      step1: 'Paristhithi ardham chesukovadam',
      step2: 'Chatta domain gurthinchadam',
      step3: 'Sambandhita nipunathanni enchukovadam',
    },
    domain: {
      identifiedPrefix: 'Domain gurthincharu:',
      detected: 'Gurthinchina domain',
      topic: 'Topic',
      intent: 'User uddesam',
    },
    recommendation: { title: 'Suchinchina Agent', reason: 'Karanam' },
    handoff: {
      handingOff: 'Handoff avutundi',
      preparing: 'Contextual handoff siddham avutundi…',
      contextExtracted: 'Context theesukunnaru',
      targetAgent: 'Target agent',
      working: 'Pani jarugutondi',
      ready: 'Siddham',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-sahaya chatta samacharam istundi, idi professional chatta salaha ki pratiga kadu.',
    },
    approval: { allow: 'Anumathinchandi', deny: 'Nirakarinchandi' },
    home: {
      title: 'Legal Setu',
      desc: 'Mee chatta prashnanu saralamaina bhashalo adagandi. Legal Orchestrator sarain domain ni gurthinchi specialist agent ni suchistundi — vaari ni add cheyalo ledo meeru nirnayistaru.',
      start: 'Chat prarambhinchandi',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu lo mee account vivaralu.',
      account: 'Account',
      fullName: 'Poorthi peru',
      email: 'Email',
      signedInVia: 'Sign in chesindi',
      memberSince: 'Member eppati nunchi',
    },
    login: {
      welcome: 'Legal Setu ki swagatham',
      desc: 'Personalized chatta margadarsakatvam kosam sign in cheyandi, mee chat charitra mariyu context mee account lo save avutundi.',
      magicSentPrefix: 'Magic link pamparu',
      magicSentSuffix: '. Mee inbox check chesi sign in avvadaniki click cheyandi.',
      redirecting: 'Google ki redirect avutundi…',
      continueGoogle: 'Google to continue cheyandi',
      or: 'leda',
      emailPlaceholder: 'meeru@example.com',
      sending: 'Link pampuvthondi…',
      sendLink: 'Magic link pampandi',
      terms: 'Continue chestunnaru ante idi oka hackathon prototype ani, professional chatta salaha ki pratiga kadani oppukuntunnaru.',
    },
  },
  kn: {
    nav: { newChat: 'ಹೊಸ ಸಂಭಾಷಣೆ', history: 'Itihaasa' },
    chat: {
      heading: 'ಇಂದು ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಗೆ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
      subheading: 'ಸರಳ ಭಾಷೆಯಲ್ಲಿ, ನಿಮಗೆ ಅನುಕೂಲಕರವಾದ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಿ.',
      placeholder: 'ನಿಮ್ಮ ಕಾನೂನು ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...',
      suggestion1: 'Ondu ottige review maadi',
      suggestion2: 'Nanna bhaadige hakkugalannu tilidukoli',
      suggestion3: 'Kanoonu suchane draft maadi',
      suggestionText1: 'Sign madukondu munche nanna bhaadige ottannu review madabahuda?',
      suggestionText2: 'Nanna maneya odeyaru security deposit hindiruguvudannu nirakarisuttiddare.',
      suggestionText3: 'Security deposit bagge maneya odeyarige kanoonu suchane draft maadabeku.',
      approvedSuffix: 'user avaru anumodisiddare',
      approvedBody: 'User suchisida specialistannu anumodisiddare. Contextual handoff siddavaguttide...',
      deniedTitle: 'Agent kelike tirasakarisalaagide',
      tryDifferent: 'Bere specialist prayatnisi',
      responseReadySuffix: 'uttara sidhavide',
      handoffBody: 'Handoff samaya haanchikonda context aadharadalli nimma specialist uttara sidhapadisiddare.',
      errorBody: 'Aa hantavannu poorti maadalaagalilla. Dayavittu punaha prayatnisi.',
      tryAgain: 'Punaha Prayatnisi',
      inputHint: 'Kaluhisalu Enter · Hosa salige Shift + Enter',
    },
    history: {
      title: 'Samvaada Itihaasa',
      subtitle: 'Legal Orchestrator jotege hindina samvaadagalannu punaha nodi.',
      empty: 'Innu samvaada itihaasavilla.',
      conversation: 'Samvaada',
      staticDemo: 'Idu ondu static demo view — poorna session ge mukhya chat ge hogi.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Nimma appearance, bhaashe, mattu samvaada data nirvahisi.',
      appearance: 'Appearance',
      appearanceDesc: 'Nimma device nalli Legal Setu hege kaanisuttade ansuvudannu aarisi.',
      theme: 'Theme',
      themeDesc: 'Light athava dark mode, samasta app nalli sync aaguttade.',
      light: 'Light',
      dark: 'Dark',
      language: 'Bhaashe',
      languageNote: 'Ee demo ge samasta site na text anuvadisalaagide.',
      interfaceLanguage: 'Interface bhaashe',
      profile: 'Profile',
      displayName: 'Display hesaru',
      conversation: 'Samvaada',
      clearHistory: 'Itihaasa tegedu haaki',
      clearedMsg: 'Samvaada itihaasa tegeyalaagide.',
      clearDesc: 'Ella saved samvaadagalannu tegedu haaki.',
      privacy: 'Privacy',
      shareData: 'Uttaragalannu sudharisalu anonymized data share maadi',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Nimma prashne analyze aaguttide…',
      step1: 'Paristhitiyannu artha maadikollodu',
      step2: 'Kanoonu domain gurutisodu',
      step3: 'Sambandhita parangatheyannu aarisodu',
    },
    domain: {
      identifiedPrefix: 'Domain gurutisalaagide:',
      detected: 'Gurutisida domain',
      topic: 'Topic',
      intent: 'User udesha',
    },
    recommendation: { title: 'Suchisida Agent', reason: 'Karana' },
    handoff: {
      handingOff: 'Handoff aaguttide',
      preparing: 'Contextual handoff siddavaguttide…',
      contextExtracted: 'Context tegedukolagide',
      targetAgent: 'Guri agent',
      working: 'Kelasa naDeyuttide',
      ready: 'Sidha',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-nerav-inda kanoonu maahiti nidutthade, idu professional kanoonu salaheya badalige alla.',
    },
    approval: { allow: 'Anumodisi', deny: 'Tirasakarisi' },
    home: {
      title: 'Legal Setu',
      desc: 'Nimma kanoonu prashneyannu saral bhaasheyalli keliri. Legal Orchestrator sariyaada domain gurutisi specialist agent annu suchisuttade — avarannu serisabeka endu neevu nirdharisuttiri.',
      start: 'Samvaada aarambhisi',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu nalli nimma account vivaragalu.',
      account: 'Account',
      fullName: 'Purna hesaru',
      email: 'Email',
      signedInVia: 'Sign in aagide',
      memberSince: 'Member yaavaga inda',
    },
    login: {
      welcome: 'Legal Setu ge swaagata',
      desc: 'Personalized kanoonu margadarshanakke sign in maadi, nimma samvaada itihaasa mattu context nimma account nalli saved aaguttade.',
      magicSentPrefix: 'Magic link kaluhisalaagide',
      magicSentSuffix: '. Nimma inbox check maadi sign in maadalu click maadi.',
      redirecting: 'Google ge redirect aaguttide…',
      continueGoogle: 'Google jotege continue maadi',
      or: 'athava',
      emailPlaceholder: 'neevu@example.com',
      sending: 'Link kaluhisuttiddare…',
      sendLink: 'Magic link kaluhisi',
      terms: 'Continue maaduva mulaka idu ondu hackathon prototype endu, professional kanoonu salaheya badalige alla endu ottukolluttiri.',
    },
  },
  gu: {
    nav: { newChat: 'નવી વાતચીત', history: 'Itihaas' },
    chat: {
      heading: 'આજે હું તમારા કાનૂની પ્રશ્નમાં કેવી રીતે મદદ કરી શકું?',
      subheading: 'સરળ ભાષામાં, તમને અનુકૂળ હોય તે ભાષામાં પૂછો.',
      placeholder: 'તમારી કાનૂની સમસ્યાનું વર્ણન કરો...',
      suggestion1: 'Karar review karo',
      suggestion2: 'Mara bhadutdar hakko janavo',
      suggestion3: 'Kanuni notice draft karo',
      suggestionText1: 'Sign karta pehla shu tame maro rental karar review karso?',
      suggestionText2: 'Maro makan-malik security deposit pacho aapva na paadi rahyo chhe.',
      suggestionText3: 'Security deposit babte makan-malikne kanuni notice draft karvani chhe.',
      approvedSuffix: 'user dvara manjur',
      approvedBody: 'User e sujaveli specialist ne manjur karyu. Contextual handoff taiyar thai rahyu chhe...',
      deniedTitle: 'Agent request nakari kadhi',
      tryDifferent: 'Biju specialist try karo',
      responseReadySuffix: 'jawab taiyar chhe',
      handoffBody: 'Tamara specialist e handoff darmiyan share thayel context na aadhare jawab taiyar karyo chhe.',
      errorBody: 'Aa step puri thai shakyu nathi. Krupa karine ferithi prayatna karo.',
      tryAgain: 'Ferithi Prayatna Karo',
      inputHint: 'Mokalva mate Enter · Navi lain mate Shift + Enter',
    },
    history: {
      title: 'Vaatchit Itihaas',
      subtitle: 'Legal Orchestrator sathe juni vaatchit jovo.',
      empty: 'Have sudhi koi vaatchit itihaas nathi.',
      conversation: 'Vaatchit',
      staticDemo: 'Aa ek static demo view chhe — purtu session mate mukhya chat par jaav.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Tamara appearance, bhasha, ane vaatchit data manage karo.',
      appearance: 'Dekhav',
      appearanceDesc: 'Tamara device par Legal Setu kevu dekhay te pasand karo.',
      theme: 'Theme',
      themeDesc: 'Light ke dark mode, aakha app ma sync thay chhe.',
      light: 'Light',
      dark: 'Dark',
      language: 'Bhasha',
      languageNote: 'Aa demo mate aakha site nu text anuvad karyu chhe.',
      interfaceLanguage: 'Interface bhasha',
      profile: 'Profile',
      displayName: 'Display naam',
      conversation: 'Vaatchit',
      clearHistory: 'Itihaas saaf karo',
      clearedMsg: 'Vaatchit itihaas saaf karyo chhe.',
      clearDesc: 'Badhi saved vaatchit dur karo.',
      privacy: 'Privacy',
      shareData: 'Jawab sudharva mate anonymized data share karo',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Tamaro prashna analyze thai rahyo chhe…',
      step1: 'Paristhiti samajvi',
      step2: 'Kanuni domain olakhvu',
      step3: 'Sambandhit nipunata pasand karvi',
    },
    domain: {
      identifiedPrefix: 'Domain olakhayu:',
      detected: 'Olakhayelu domain',
      topic: 'Vishay',
      intent: 'User no hetu',
    },
    recommendation: { title: 'Sujavel Agent', reason: 'Karan' },
    handoff: {
      handingOff: 'Handoff thai rahyu chhe',
      preparing: 'Contextual handoff taiyar thai rahyu chhe…',
      contextExtracted: 'Context kadhyu',
      targetAgent: 'Target agent',
      working: 'Kaam chalu chhe',
      ready: 'Taiyar',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-sahayta thi kanuni mahiti aape chhe ane professional kanuni salah no vikalp nathi.',
    },
    approval: { allow: 'Manjur', deny: 'Nakari kadhvu' },
    home: {
      title: 'Legal Setu',
      desc: 'Tamaro kanuni prashna saral bhashama puchho. Legal Orchestrator sachi domain olakhi ne specialist agent sujave chhe — temne saamel karva ke nahi te tame nakki karo chho.',
      start: 'Vaatchit shru karo',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu par tamara account ni details.',
      account: 'Account',
      fullName: 'Puru naam',
      email: 'Email',
      signedInVia: 'Sign in karyu',
      memberSince: 'Member kyare thi',
    },
    login: {
      welcome: 'Legal Setu ma tamaru swagat chhe',
      desc: 'Personalized kanuni margdarshan mate sign in karo, tamari vaatchit itihaas ane context tamara account ma saved rahese.',
      magicSentPrefix: 'Magic link mokalyo',
      magicSentSuffix: '. Tamaro inbox check karo ane sign in karva mate click karo.',
      redirecting: 'Google par redirect thai rahyu chhe…',
      continueGoogle: 'Google sathe continue karo',
      or: 'ke',
      emailPlaceholder: 'tame@example.com',
      sending: 'Link mokalai rahyo chhe…',
      sendLink: 'Magic link mokalo',
      terms: 'Continue karine tame sahmat thao chho ke aa ek hackathon prototype chhe, professional kanuni salah no vikalp nathi.',
    },
  },
  ur: {
    nav: { newChat: 'نئی گفتگو' },
    chat: {
      heading: 'آج میں آپ کے قانونی سوال میں کیسے مدد کر سکتا ہوں؟',
      subheading: 'سادہ زبان میں، اس زبان میں پوچھیں جس میں آپ آسانی محسوس کرتے ہیں۔',
      placeholder: 'اپنا قانونی مسئلہ بیان کریں...',
    },
  },
  or: {
    nav: { newChat: 'ନୂଆ ଚାଟ୍' },
    chat: {
      heading: 'ଆଜି ମୁଁ ଆପଣଙ୍କ ଆଇନଗତ ପ୍ରଶ୍ନରେ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
      subheading: 'ସରଳ ଭାଷାରେ, ଆପଣ ସହଜ ଅନୁଭବ କରୁଥିବା ଭାଷାରେ ପଚାରନ୍ତୁ।',
      placeholder: 'ଆପଣଙ୍କ ଆଇନଗତ ସମସ୍ୟା ବର୍ଣ୍ଣନା କରନ୍ତୁ...',
    },
  },
  pa: {
    nav: { newChat: 'ਨਵੀਂ ਗੱਲਬਾਤ' },
    chat: {
      heading: 'ਅੱਜ ਮੈਂ ਤੁਹਾਡੇ ਕਾਨੂੰਨੀ ਸਵਾਲ ਵਿੱਚ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?',
      subheading: 'ਸਾਦੀ ਭਾਸ਼ਾ ਵਿੱਚ, ਜਿਸ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਸੀਂ ਸਹਿਜ ਹੋ, ਪੁੱਛੋ।',
      placeholder: 'ਆਪਣੀ ਕਾਨੂੰਨੀ ਸਮੱਸਿਆ ਦੱਸੋ...',
    },
  },
  ml: {
    nav: { newChat: 'പുതിയ ചാറ്റ്' },
    chat: {
      heading: 'ഇന്ന് നിങ്ങളുടെ നിയമപരമായ ചോദ്യത്തിൽ ഞാൻ എങ്ങനെ സഹായിക്കാം?',
      subheading: 'ലളിതമായ ഭാഷയിൽ, നിങ്ങൾക്ക് സൗകര്യപ്രദമായ ഭാഷയിൽ ചോദിക്കുക.',
      placeholder: 'നിങ്ങളുടെ നിയമപ്രശ്നം വിവരിക്കുക...',
    },
  },
  as: {
    nav: { newChat: 'নতুন আলাপ' },
    chat: {
      heading: 'আজি মই আপোনাৰ আইনী প্ৰশ্নত কেনেকৈ সহায় কৰিব পাৰোঁ?',
      subheading: 'সহজ ভাষাত, আপুনি সহজ অনুভৱ কৰা ভাষাত সোধক।',
      placeholder: 'আপোনাৰ আইনী সমস্যা বৰ্ণনা কৰক...',
    },
  },
  mai: {
    nav: { newChat: 'नव बातचीत' },
    chat: {
      heading: 'आइ हम अहाँक कानूनी प्रश्नमे कोना मदद क सकैत छी?',
      subheading: 'सरल भाषामे, जे भाषामे अहाँ सहज होई से पूछू।',
      placeholder: 'अपन कानूनी समस्या वर्णन करू...',
    },
  },
  sa: {
    nav: { newChat: 'नूतनं संभाषणम्' },
    chat: {
      heading: 'अद्य अहं भवतः विधिविषयकं प्रश्नं कथं साहाय्यं कर्तुं शक्नोमि?',
      subheading: 'सरलभाषायां, या भाषा भवते सुगमा तस्यां पृच्छतु।',
      placeholder: 'स्वकीयां विधिसमस्यां वर्णयतु...',
    },
  },
  ks: {
    nav: { newChat: 'नव गुफ्तगू' },
    chat: {
      heading: 'आज़ मैं तोहनिस कानूनी सवालस मंज़ किताह मदद करी हेकां?',
      subheading: 'आसान ज़बानि मंज़, यि ज़बान तोहय आसान लगान, तिमी पुछिव।',
      placeholder: 'पनुन कानूनी मसला बयान करिव...',
    },
  },
  ne: {
    nav: { newChat: 'नयाँ कुराकानी' },
    chat: {
      heading: 'आज म तपाईंको कानूनी प्रश्नमा कसरी मद्दत गर्न सक्छु?',
      subheading: 'सरल भाषामा, तपाईंलाई सहज लाग्ने भाषामा सोध्नुहोस्।',
      placeholder: 'तपाईंको कानूनी समस्या वर्णन गर्नुहोस्...',
    },
  },
  kok: {
    nav: { newChat: 'नवें संभाषण' },
    chat: {
      heading: 'आज हांव तुमच्या कायदेशीर प्रस्नांत कशी मदत करूं येता?',
      subheading: 'सोप्या भाशेंत, तुमकां सुविधायेची भास वापरून विचारात.',
      placeholder: 'तुमची कायदेशीर समस्या वर्णन करात...',
    },
  },
  sd: {
    nav: { newChat: 'نئين ڳالهه ٻولهه' },
    chat: {
      heading: 'اڄ مان توهانجي قانوني سوال ۾ ڪيئن مدد ڪري سگهان ٿو؟',
      subheading: 'سولي ٻولي ۾، جيڪا ٻولي توهان کي آسان لڳي تنهن ۾ پڇو.',
      placeholder: 'پنهنجي قانوني مسئلي جو بيان ڪريو...',
    },
  },
  doi: {
    nav: { newChat: 'नमीं गल्लबात' },
    chat: {
      heading: 'अज्ज मैं तुंदे कानूनी सवाल च कि मदद करी सकनै?',
      subheading: 'सोखी भाशा च, जिस भाशा च तुसें आसान लगदा पुच्छो।',
      placeholder: 'आपणी कानूनी समस्या दस्सो...',
    },
  },
  mni: {
    nav: { newChat: 'ꯋꯥꯔꯤ ꯑꯅꯧꯕ' },
    chat: {
      heading: 'ꯉꯁꯤ ꯑꯩꯅ ꯅꯪꯒꯤ ꯋꯥꯌꯦꯜ ꯑꯁꯤꯗ ꯀꯔꯝꯅ ꯃꯇꯦꯡ ꯄꯥꯡꯒꯅꯤ?',
      subheading: 'ꯄꯥꯡꯒꯜ ꯂꯣꯟꯗ, ꯅꯪꯅ ꯆꯪꯅ ꯉꯝꯅꯕ ꯂꯣꯟꯗ ꯍꯪꯕꯤꯌꯨ.',
      placeholder: 'ꯅꯪꯒꯤ ꯋꯥꯌꯦꯜ ꯋꯥꯐꯝ ꯍꯥꯢꯕꯤꯌꯨ...',
    },
  },
  sat: {
    nav: { newChat: 'नावा रोड़ो' },
    chat: {
      heading: 'तिंगिन आम आम रेयाक़ आइनी प्रोस्नो रे चेत लेकान मदद दाड़ेयाम?',
      subheading: 'सोलोमोन पारसिक ते, जाहान पारसिक आमाक़ सोलोमोन लागोआ ओना ते कुली मे.',
      placeholder: 'आमाक़ आइनी गोंडेय ओलाओ मे...',
    },
  },
  brx: {
    nav: { newChat: 'गोदान सल्लाहनाय' },
    chat: {
      heading: 'दिनै आं नोंथाङा कानूनी प्रश्नाव मोन्दिनि दा गोहो होनो हागौ?',
      subheading: 'सुबुं फोरमानि रावजों, नोंथाङा गोहो जागायथारि रावजों सुंगोन।',
      placeholder: 'नोंथाङनि कानूनी समस्याखौ फोरमायदों...',
    },
  },
};

export function AppProvider({ children }) {
  const { user } = useAuth();
  const [language, setLanguage] = useState('en');
  const [historyCleared, setHistoryCleared] = useState(false);
  const [displayName, setDisplayName] = useState('');
  const [nameEdited, setNameEdited] = useState(false);

  // Default the display name from the signed-in account until the user
  // edits it themselves in Settings.
  useEffect(() => {
    if (nameEdited) return;
    const fallback = user?.user_metadata?.full_name || user?.email?.split('@')[0] || '';
    setDisplayName(fallback);
  }, [user, nameEdited]);

  const updateDisplayName = useCallback((name) => {
    setNameEdited(true);
    setDisplayName(name);
  }, []);

  const t = useCallback(
    (key) => {
      const path = key.split('.');
      const lookup = (dict) => path.reduce((acc, part) => (acc == null ? acc : acc[part]), dict);
      return lookup(STRINGS[language]) ?? lookup(STRINGS.en) ?? key;
    },
    [language]
  );

  const clearHistory = useCallback(() => setHistoryCleared(true), []);

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        t,
        historyCleared,
        clearHistory,
        displayName,
        setDisplayName: updateDisplayName,
      }}
    >
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}
