import { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { useAuth } from './AuthContext.jsx';

const AppContext = createContext(null);

// English + all languages listed in the Eighth Schedule of the Constitution of India.
// `label` is the language's own native name (not an English translation of it).
export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'mr', label: 'मराठी' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'ur', label: 'اردو' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'or', label: 'ଓଡ଼ିଆ' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'as', label: 'অসমীয়া' },
  { code: 'mai', label: 'मैथिली' },
  { code: 'sa', label: 'संस्कृतम्' },
  { code: 'ks', label: 'کٲشُر' },
  { code: 'ne', label: 'नेपाली' },
  { code: 'kok', label: 'कोंकणी' },
  { code: 'sd', label: 'سنڌي' },
  { code: 'doi', label: 'डोगरी' },
  { code: 'mni', label: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { code: 'sat', label: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'brx', label: 'बड़ो' },
];

// Site-wide UI copy, keyed by dot-path (e.g. "chat.heading"). t() falls back
// to English for any key missing in the active language, so partial
// coverage degrades gracefully instead of breaking.
//
// The 8 languages below (en/hi/mr/bn/ta/te/kn/gu) have full site coverage:
// core strings (nav.newChat, chat.heading/subheading/placeholder) are in
// native script, translated by a previous PR; everything else here is a
// romanized (Latin-script) demo translation, not proofread by a native
// speaker. The remaining 14 Eighth Schedule languages only have those core
// native-script strings -- everything else falls back to English.
// Legal document pages (Privacy Policy, Terms of Service) and the agent
// descriptions in data/agents.js are intentionally left in English:
// mistranslated legal text is worse than none.
const STRINGS = {
  en: {
    nav: { newChat: 'New Chat', history: 'History' },
    chat: {
      heading: 'How can I help with your legal question today?',
      subheading: 'Ask in plain language, in the language you are most comfortable with.',
      placeholder: 'Describe your legal problem...',
      suggestion1: 'Review a contract',
      suggestion2: 'Know my tenant rights',
      suggestion3: 'Draft a legal notice',
      suggestionText1: 'Can you review my rental contract before I sign it?',
      suggestionText2: 'My landlord is refusing to return my security deposit.',
      suggestionText3: 'I need to draft a legal notice to my landlord about my security deposit.',
      approvedSuffix: 'approved by user',
      approvedBody: 'User approved the recommended specialist. Preparing a contextual handoff...',
      deniedTitle: 'Agent request denied',
      tryDifferent: 'Try a different specialist',
      responseReadySuffix: 'response ready',
      handoffBody: 'Your specialist has prepared a response based on the context shared during handoff.',
      errorBody: "We couldn't complete that step. Please try again.",
      tryAgain: 'Try Again',
      inputHint: 'Enter to send · Shift + Enter for a new line',
    },
    history: {
      title: 'Conversation History',
      subtitle: 'Revisit past conversations with the Legal Orchestrator.',
      empty: 'No conversation history yet.',
      conversation: 'Conversation',
      staticDemo: 'This is a static demo view — reopen a full session from the primary chat experience.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Manage your appearance, language, and conversation data.',
      appearance: 'Appearance',
      appearanceDesc: 'Choose how Legal Setu looks on your device.',
      theme: 'Theme',
      themeDesc: 'Light or dark mode, synced across the app.',
      light: 'Light',
      dark: 'Dark',
      language: 'Language',
      languageNote: 'Interface text is translated across the whole site for this demo.',
      interfaceLanguage: 'Interface language',
      profile: 'Profile',
      displayName: 'Display name',
      conversation: 'Conversation',
      clearHistory: 'Clear history',
      clearedMsg: 'Conversation history has been cleared.',
      clearDesc: 'Remove all saved conversations.',
      privacy: 'Privacy',
      shareData: 'Share anonymized data to improve responses',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'Analyzing your query…',
      step1: 'Understanding the situation',
      step2: 'Identifying legal domain',
      step3: 'Selecting relevant expertise',
    },
    domain: {
      identifiedPrefix: 'Domain identified:',
      detected: 'Detected domain',
      topic: 'Topic',
      intent: 'User intent',
    },
    recommendation: { title: 'Recommended Agent', reason: 'Reason' },
    handoff: {
      handingOff: 'Handing off',
      preparing: 'Preparing contextual handoff…',
      contextExtracted: 'Context extracted',
      targetAgent: 'Target agent',
      working: 'Working',
      ready: 'Ready',
      contextualHandoff: 'contextual handoff',
    },
    agentResponse: {
      disclaimer: 'Legal Setu provides AI-assisted legal information and does not replace professional legal advice.',
    },
    approval: { allow: 'Allow', deny: 'Deny' },
    home: {
      title: 'Legal Setu',
      desc: 'Ask your legal question in plain language. The Legal Orchestrator identifies the right domain and recommends a specialist agent — you decide whether to bring them in.',
      start: 'Start a conversation',
    },
    profile: {
      title: 'Profile',
      desc: 'Your account details on Legal Setu.',
      account: 'Account',
      fullName: 'Full name',
      email: 'Email',
      signedInVia: 'Signed in via',
      memberSince: 'Member since',
    },
    login: {
      welcome: 'Welcome to Legal Setu',
      desc: 'Sign in to get personalized legal guidance, with your conversation history and context saved to your account.',
      magicSentPrefix: 'Magic link sent to',
      magicSentSuffix: '. Check your inbox and click it to sign in.',
      redirecting: 'Redirecting to Google…',
      continueGoogle: 'Continue with Google',
      or: 'or',
      emailPlaceholder: 'you@example.com',
      sending: 'Sending link…',
      sendLink: 'Send magic link',
      terms: 'By continuing you agree this is a hackathon prototype, not a substitute for professional legal advice.',
    },
  },
  hi: {
    nav: { newChat: 'नई बातचीत', history: 'इतिहास' },
    chat: {
      heading: 'आज मैं आपके कानूनी प्रश्न में कैसे मदद कर सकता हूँ?',
      subheading: 'सरल भाषा में, अपनी पसंदीदा भाषा में पूछें।',
      placeholder: 'अपनी कानूनी समस्या बताएं...',
      suggestion1: 'एक अनुबंध की समीक्षा करें',
      suggestion2: 'अपने किरायेदार अधिकार जानें',
      suggestion3: 'कानूनी नोटिस का मसौदा तैयार करें',
      suggestionText1: 'क्या आप हस्ताक्षर करने से पहले मेरा किराया अनुबंध जांच सकते हैं?',
      suggestionText2: 'मेरा मकान-मालिक सिक्योरिटी डिपॉज़िट वापस नहीं दे रहा है।',
      suggestionText3: 'मुझे सिक्योरिटी डिपॉज़िट के बारे में मकान-मालिक को कानूनी नोटिस भेजना है।',
      approvedSuffix: 'यूज़र द्वारा मंज़ूर',
      approvedBody: 'यूज़र ने सुझाए गए विशेषज्ञ को मंज़ूरी दी। संदर्भ सहित हैंडऑफ़ तैयार हो रहा है...',
      deniedTitle: 'एजेंट का अनुरोध अस्वीकृत',
      tryDifferent: 'कोई दूसरा विशेषज्ञ आज़माएं',
      responseReadySuffix: 'जवाब तैयार है',
      handoffBody: 'आपके विशेषज्ञ ने हैंडऑफ़ के दौरान साझा किए गए संदर्भ के आधार पर जवाब तैयार किया है।',
      errorBody: 'यह चरण पूरा नहीं हो सका। कृपया दोबारा प्रयास करें।',
      tryAgain: 'दोबारा प्रयास करें',
      inputHint: 'भेजने के लिए Enter · नई पंक्ति के लिए Shift + Enter',
    },
    history: {
      title: 'बातचीत का इतिहास',
      subtitle: 'लीगल ऑर्केस्ट्रेटर के साथ पुरानी बातचीत देखें।',
      empty: 'अभी तक कोई बातचीत का इतिहास नहीं है।',
      conversation: 'बातचीत',
      staticDemo: 'यह एक स्थिर डेमो दृश्य है — पूरा सत्र शुरू करने के लिए मुख्य चैट पर जाएं।',
    },
    settings: {
      title: 'सेटिंग्स',
      subtitle: 'अपना रूप-रंग, भाषा और बातचीत का डेटा प्रबंधित करें।',
      appearance: 'रूप-रंग',
      appearanceDesc: 'चुनें कि लीगल सेतु आपके डिवाइस पर कैसा दिखे।',
      theme: 'थीम',
      themeDesc: 'लाइट या डार्क मोड, पूरे ऐप में समन्वित रहता है।',
      light: 'लाइट',
      dark: 'डार्क',
      language: 'भाषा',
      languageNote: 'इस डेमो के लिए पूरी साइट का टेक्स्ट अनुवादित किया गया है।',
      interfaceLanguage: 'इंटरफ़ेस भाषा',
      profile: 'प्रोफ़ाइल',
      displayName: 'प्रदर्शित नाम',
      conversation: 'बातचीत',
      clearHistory: 'इतिहास साफ़ करें',
      clearedMsg: 'बातचीत का इतिहास साफ़ कर दिया गया है।',
      clearDesc: 'सभी सहेजी गई बातचीत हटाएं।',
      privacy: 'गोपनीयता',
      shareData: 'जवाब बेहतर बनाने के लिए अनाम डेटा साझा करें',
      usageAnalytics: 'उपयोग विश्लेषण',
    },
    userMenu: {
      profile: 'प्रोफ़ाइल',
      settings: 'सेटिंग्स',
      theme: 'थीम',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      signOut: 'साइन आउट',
    },
    orchestrator: {
      title: 'लीगल ऑर्केस्ट्रेटर',
      analyzing: 'आपके प्रश्न का विश्लेषण हो रहा है…',
      step1: 'स्थिति को समझना',
      step2: 'कानूनी क्षेत्र की पहचान करना',
      step3: 'संबंधित विशेषज्ञता चुनना',
    },
    domain: {
      identifiedPrefix: 'क्षेत्र पहचाना गया:',
      detected: 'पहचाना गया क्षेत्र',
      topic: 'विषय',
      intent: 'यूज़र का इरादा',
    },
    recommendation: { title: 'सुझाया गया एजेंट', reason: 'कारण' },
    handoff: {
      handingOff: 'हैंडऑफ़ हो रहा है',
      preparing: 'संदर्भ सहित हैंडऑफ़ तैयार हो रहा है…',
      contextExtracted: 'संदर्भ निकाला गया',
      targetAgent: 'लक्षित एजेंट',
      working: 'काम चल रहा है',
      ready: 'तैयार',
      contextualHandoff: 'संदर्भ सहित हैंडऑफ़',
    },
    agentResponse: {
      disclaimer: 'लीगल सेतु AI-सहायता प्राप्त कानूनी जानकारी देता है और पेशेवर कानूनी सलाह का विकल्प नहीं है।',
    },
    approval: { allow: 'मंज़ूर करें', deny: 'अस्वीकार करें' },
    home: {
      title: 'Legal Setu',
      desc: 'अपना कानूनी सवाल सरल भाषा में पूछें। लीगल ऑर्केस्ट्रेटर सही क्षेत्र पहचानता है और एक विशेषज्ञ एजेंट सुझाता है — उसे शामिल करना है या नहीं, यह आप तय करते हैं।',
      start: 'बातचीत शुरू करें',
    },
    profile: {
      title: 'प्रोफ़ाइल',
      desc: 'लीगल सेतु पर आपके खाते का विवरण।',
      account: 'खाता',
      fullName: 'पूरा नाम',
      email: 'ईमेल',
      signedInVia: 'इसके ज़रिए साइन इन किया',
      memberSince: 'सदस्य कब से हैं',
    },
    login: {
      welcome: 'लीगल सेतु में आपका स्वागत है',
      desc: 'व्यक्तिगत कानूनी मार्गदर्शन के लिए साइन इन करें, आपकी बातचीत का इतिहास और संदर्भ आपके खाते में सहेजा रहेगा।',
      magicSentPrefix: 'मैजिक लिंक भेज दिया गया',
      magicSentSuffix: '. अपना इनबॉक्स जांचें और साइन इन करने के लिए उस पर क्लिक करें।',
      redirecting: 'Google पर रीडायरेक्ट हो रहा है…',
      continueGoogle: 'Google से जारी रखें',
      or: 'या',
      emailPlaceholder: 'aap@example.com',
      sending: 'लिंक भेजा जा रहा है…',
      sendLink: 'मैजिक लिंक भेजें',
      terms: 'जारी रखकर आप सहमत होते हैं कि यह एक हैकाथॉन प्रोटोटाइप है, पेशेवर कानूनी सलाह का विकल्प नहीं।',
    },
  },
  mr: {
    nav: { newChat: 'नवीन संभाषण', history: 'इतिहास' },
    chat: {
      heading: 'आज मी तुमच्या कायदेशीर प्रश्नात कशी मदत करू शकतो?',
      subheading: 'सोप्या भाषेत, तुम्हाला सोयीस्कर असलेल्या भाषेत विचारा.',
      placeholder: 'तुमची कायदेशीर समस्या सांगा...',
      suggestion1: 'करार तपासून घ्या',
      suggestion2: 'भाडेकरू म्हणून तुमचे हक्क जाणून घ्या',
      suggestion3: 'कायदेशीर नोटीस तयार करा',
      suggestionText1: 'सही करण्यापूर्वी माझा भाडे करार तपासाल का?',
      suggestionText2: 'माझा घरमालक सुरक्षा ठेव परत द्यायला नकार देत आहे.',
      suggestionText3: 'मला सुरक्षा ठेवीबाबत घरमालकाला कायदेशीर नोटीस पाठवायची आहे.',
      approvedSuffix: 'वापरकर्त्याने मंजूर केले',
      approvedBody: 'वापरकर्त्याने सुचवलेल्या तज्ज्ञाला मंजुरी दिली. संदर्भासह हस्तांतरण तयार होत आहे...',
      deniedTitle: 'एजंटची विनंती नाकारली',
      tryDifferent: 'दुसरा तज्ज्ञ निवडून पाहा',
      responseReadySuffix: 'उत्तर तयार आहे',
      handoffBody: 'तुमच्या तज्ज्ञाने हस्तांतरणादरम्यान मिळालेल्या संदर्भावरून उत्तर तयार केले आहे.',
      errorBody: 'हा टप्पा पूर्ण होऊ शकला नाही. कृपया पुन्हा प्रयत्न करा.',
      tryAgain: 'पुन्हा प्रयत्न करा',
      inputHint: 'पाठवण्यासाठी Enter · नवीन ओळीसाठी Shift + Enter',
    },
    history: {
      title: 'संभाषणाचा इतिहास',
      subtitle: 'लीगल ऑर्केस्ट्रेटरसोबतची जुनी संभाषणे पुन्हा पाहा.',
      empty: 'अद्याप कोणताही संभाषण इतिहास नाही.',
      conversation: 'संभाषण',
      staticDemo: 'हे एक स्थिर डेमो दृश्य आहे — पूर्ण सत्रासाठी मुख्य चॅटवर परत जा.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'तुमचे स्वरूप, भाषा आणि संभाषण डेटा व्यवस्थापित करा.',
      appearance: 'स्वरूप',
      appearanceDesc: 'लीगल सेतू तुमच्या डिव्हाइसवर कसे दिसेल ते निवडा.',
      theme: 'Theme',
      themeDesc: 'Light किंवा Dark मोड, संपूर्ण अ‍ॅपमध्ये समक्रमित होतो.',
      light: 'Light',
      dark: 'Dark',
      language: 'भाषा',
      languageNote: 'या डेमोसाठी संपूर्ण साइटचा मजकूर भाषांतरित करण्यात आला आहे.',
      interfaceLanguage: 'इंटरफेस भाषा',
      profile: 'Profile',
      displayName: 'प्रदर्शित नाव',
      conversation: 'संभाषण',
      clearHistory: 'इतिहास साफ करा',
      clearedMsg: 'संभाषणाचा इतिहास साफ करण्यात आला आहे.',
      clearDesc: 'सर्व जतन केलेली संभाषणे काढून टाका.',
      privacy: 'Privacy',
      shareData: 'उत्तरे सुधारण्यासाठी अज्ञात डेटा सामायिक करा',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'लीगल ऑर्केस्ट्रेटर',
      analyzing: 'तुमच्या प्रश्नाचे विश्लेषण होत आहे…',
      step1: 'परिस्थिती समजून घेणे',
      step2: 'कायदेशीर क्षेत्र ओळखणे',
      step3: 'संबंधित तज्ज्ञता निवडणे',
    },
    domain: {
      identifiedPrefix: 'क्षेत्र ओळखले गेले:',
      detected: 'ओळखलेले क्षेत्र',
      topic: 'विषय',
      intent: 'वापरकर्त्याचा हेतू',
    },
    recommendation: { title: 'सुचवलेला एजंट', reason: 'कारण' },
    handoff: {
      handingOff: 'हस्तांतरण होत आहे',
      preparing: 'संदर्भासह हस्तांतरण तयार होत आहे…',
      contextExtracted: 'संदर्भ काढला',
      targetAgent: 'लक्ष्य एजंट',
      working: 'काम सुरू आहे',
      ready: 'तयार',
      contextualHandoff: 'संदर्भासह हस्तांतरण',
    },
    agentResponse: {
      disclaimer: 'लीगल सेतू AI-आधारित कायदेशीर माहिती देते आणि व्यावसायिक कायदेशीर सल्ल्याचा पर्याय नाही.',
    },
    approval: { allow: 'मंजूर करा', deny: 'नाकारा' },
    home: {
      title: 'Legal Setu',
      desc: 'तुमचा कायदेशीर प्रश्न सोप्या भाषेत विचारा. लीगल ऑर्केस्ट्रेटर योग्य क्षेत्र ओळखतो आणि तज्ज्ञ एजंट सुचवतो — त्याला सामील करायचे की नाही हे तुम्ही ठरवता.',
      start: 'संभाषण सुरू करा',
    },
    profile: {
      title: 'प्रोफाइल',
      desc: 'लीगल सेतूवरील तुमच्या खात्याचा तपशील.',
      account: 'खाते',
      fullName: 'पूर्ण नाव',
      email: 'Email',
      signedInVia: 'याद्वारे साइन इन केले',
      memberSince: 'सदस्य कधीपासून',
    },
    login: {
      welcome: 'लीगल सेतूमध्ये आपले स्वागत आहे',
      desc: 'वैयक्तिकृत कायदेशीर मार्गदर्शनासाठी साइन इन करा, तुमचा संभाषण इतिहास आणि संदर्भ तुमच्या खात्यात जतन राहील.',
      magicSentPrefix: 'मॅजिक लिंक पाठवली',
      magicSentSuffix: '. तुमचा इनबॉक्स तपासा आणि साइन इन करण्यासाठी त्यावर क्लिक करा.',
      redirecting: 'Google कडे पुनर्निर्देशित होत आहे…',
      continueGoogle: 'Google सह सुरू ठेवा',
      or: 'किंवा',
      emailPlaceholder: 'tumhi@example.com',
      sending: 'लिंक पाठवत आहोत…',
      sendLink: 'मॅजिक लिंक पाठवा',
      terms: 'सुरू ठेवून तुम्ही मान्य करता की हा एक हॅकेथॉन प्रोटोटाइप आहे, व्यावसायिक कायदेशीर सल्ल्याचा पर्याय नाही.',
    },
  },
  bn: {
    nav: { newChat: 'নতুন আলাপ', history: 'ইতিহাস' },
    chat: {
      heading: 'আজ আমি আপনার আইনি প্রশ্নে কীভাবে সাহায্য করতে পারি?',
      subheading: 'সহজ ভাষায়, আপনার পছন্দের ভাষায় জিজ্ঞাসা করুন।',
      placeholder: 'আপনার আইনি সমস্যা বর্ণনা করুন...',
      suggestion1: 'একটি চুক্তি পর্যালোচনা করুন',
      suggestion2: 'ভাড়াটিয়ার অধিকার জানুন',
      suggestion3: 'আইনি নোটিশ তৈরি করুন',
      suggestionText1: 'সই করার আগে আমার ভাড়ার চুক্তিটি একটু দেখে দেবেন?',
      suggestionText2: 'আমার বাড়িওয়ালা নিরাপত্তা জামানত ফেরত দিতে রাজি হচ্ছেন না।',
      suggestionText3: 'নিরাপত্তা জামানত নিয়ে আমার বাড়িওয়ালাকে একটি আইনি নোটিশ পাঠাতে হবে।',
      approvedSuffix: 'ব্যবহারকারী দ্বারা অনুমোদিত',
      approvedBody: 'ব্যবহারকারী প্রস্তাবিত বিশেষজ্ঞকে অনুমোদন দিয়েছেন। প্রাসঙ্গিক হস্তান্তর প্রস্তুত করা হচ্ছে...',
      deniedTitle: 'এজেন্টের অনুরোধ প্রত্যাখ্যাত হয়েছে',
      tryDifferent: 'অন্য বিশেষজ্ঞ চেষ্টা করুন',
      responseReadySuffix: 'উত্তর প্রস্তুত',
      handoffBody: 'হস্তান্তরের সময় শেয়ার করা প্রসঙ্গ অনুযায়ী আপনার বিশেষজ্ঞ একটি উত্তর প্রস্তুত করেছেন।',
      errorBody: 'এই ধাপটি সম্পূর্ণ করা যায়নি। দয়া করে আবার চেষ্টা করুন।',
      tryAgain: 'আবার চেষ্টা করুন',
      inputHint: 'পাঠাতে Enter · নতুন লাইনের জন্য Shift + Enter',
    },
    history: {
      title: 'আলাপের ইতিহাস',
      subtitle: 'লিগ্যাল অর্কেস্ট্রেটরের সাথে পুরনো আলাপ আবার দেখুন।',
      empty: 'এখনও কোনো আলাপের ইতিহাস নেই।',
      conversation: 'আলাপ',
      staticDemo: 'এটি একটি স্ট্যাটিক ডেমো ভিউ — সম্পূর্ণ সেশনের জন্য মূল চ্যাট থেকে আবার খুলুন।',
    },
    settings: {
      title: 'সেটিংস',
      subtitle: 'আপনার অ্যাপিয়ারেন্স, ভাষা এবং আলাপের ডেটা পরিচালনা করুন।',
      appearance: 'অ্যাপিয়ারেন্স',
      appearanceDesc: 'আপনার ডিভাইসে Legal Setu কেমন দেখাবে তা বেছে নিন।',
      theme: 'থিম',
      themeDesc: 'লাইট বা ডার্ক মোড, পুরো অ্যাপ জুড়ে সিঙ্ক করা।',
      light: 'Light',
      dark: 'Dark',
      language: 'ভাষা',
      languageNote: 'এই ডেমোর জন্য পুরো সাইটের টেক্সট অনুবাদ করা হয়েছে।',
      interfaceLanguage: 'ইন্টারফেস ভাষা',
      profile: 'Profile',
      displayName: 'প্রদর্শিত নাম',
      conversation: 'আলাপ',
      clearHistory: 'ইতিহাস মুছুন',
      clearedMsg: 'আলাপের ইতিহাস মুছে ফেলা হয়েছে।',
      clearDesc: 'সংরক্ষিত সমস্ত আলাপ সরিয়ে দিন।',
      privacy: 'Privacy',
      shareData: 'উত্তর আরও ভালো করতে বেনামী ডেটা শেয়ার করুন',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'লিগ্যাল অর্কেস্ট্রেটর',
      analyzing: 'আপনার প্রশ্ন বিশ্লেষণ করা হচ্ছে…',
      step1: 'পরিস্থিতি বোঝা হচ্ছে',
      step2: 'আইনি ক্ষেত্র চিহ্নিত করা হচ্ছে',
      step3: 'প্রাসঙ্গিক বিশেষজ্ঞতা বেছে নেওয়া হচ্ছে',
    },
    domain: {
      identifiedPrefix: 'ক্ষেত্র চিহ্নিত হয়েছে:',
      detected: 'শনাক্তকৃত ক্ষেত্র',
      topic: 'বিষয়',
      intent: 'ব্যবহারকারীর উদ্দেশ্য',
    },
    recommendation: { title: 'প্রস্তাবিত এজেন্ট', reason: 'কারণ' },
    handoff: {
      handingOff: 'হস্তান্তর করা হচ্ছে',
      preparing: 'প্রাসঙ্গিক হস্তান্তর প্রস্তুত করা হচ্ছে…',
      contextExtracted: 'প্রসঙ্গ সংগ্রহ করা হয়েছে',
      targetAgent: 'লক্ষ্য এজেন্ট',
      working: 'কাজ চলছে',
      ready: 'প্রস্তুত',
      contextualHandoff: 'প্রাসঙ্গিক হস্তান্তর',
    },
    agentResponse: {
      disclaimer: 'Legal Setu এআই-সহায়িত আইনি তথ্য প্রদান করে এবং পেশাদার আইনি পরামর্শের বিকল্প নয়।',
    },
    approval: { allow: 'অনুমোদন করুন', deny: 'প্রত্যাখ্যান করুন' },
    home: {
      title: 'Legal Setu',
      desc: 'আপনার আইনি প্রশ্ন সহজ ভাষায় জিজ্ঞাসা করুন। লিগ্যাল অর্কেস্ট্রেটর সঠিক ক্ষেত্র চিহ্নিত করে এবং একজন বিশেষজ্ঞ এজেন্ট প্রস্তাব করে — তাদের যুক্ত করবেন কিনা তা আপনি ঠিক করবেন।',
      start: 'একটি আলাপ শুরু করুন',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu-তে আপনার অ্যাকাউন্টের বিবরণ।',
      account: 'অ্যাকাউন্ট',
      fullName: 'পুরো নাম',
      email: 'Email',
      signedInVia: 'যেভাবে সাইন ইন করা হয়েছে',
      memberSince: 'সদস্য যেদিন থেকে',
    },
    login: {
      welcome: 'Legal Setu-তে আপনাকে স্বাগতম',
      desc: 'ব্যক্তিগতকৃত আইনি নির্দেশনা পেতে সাইন ইন করুন, আপনার আলাপের ইতিহাস ও প্রসঙ্গ আপনার অ্যাকাউন্টে সংরক্ষিত থাকবে।',
      magicSentPrefix: 'ম্যাজিক লিঙ্ক পাঠানো হয়েছে',
      magicSentSuffix: '। সাইন ইন করতে আপনার ইনবক্স দেখুন এবং লিঙ্কে ক্লিক করুন।',
      redirecting: 'Google-এ রিডাইরেক্ট করা হচ্ছে…',
      continueGoogle: 'Google দিয়ে চালিয়ে যান',
      or: 'অথবা',
      emailPlaceholder: 'apni@example.com',
      sending: 'লিঙ্ক পাঠানো হচ্ছে…',
      sendLink: 'ম্যাজিক লিঙ্ক পাঠান',
      terms: 'চালিয়ে গেলে আপনি সম্মত হচ্ছেন যে এটি একটি হ্যাকাথন প্রোটোটাইপ, পেশাদার আইনি পরামর্শের বিকল্প নয়।',
    },
  },
  ta: {
    nav: { newChat: 'புதிய உரையாடல்', history: 'வரலாறு' },
    chat: {
      heading: 'இன்று உங்கள் சட்டப் பிரச்சினைக்கு நான் எப்படி உதவ முடியும்?',
      subheading: 'எளிய மொழியில், நீங்கள் வசதியாக உணரும் மொழியில் கேளுங்கள்.',
      placeholder: 'உங்கள் சட்டப் பிரச்சினையை விவரிக்கவும்...',
      suggestion1: 'ஒரு ஒப்பந்தத்தை மதிப்பாய்வு செய்யவும்',
      suggestion2: 'என் குடியிருப்பாளர் உரிமைகளை அறியவும்',
      suggestion3: 'சட்ட அறிவிப்பு ஒன்றை உருவாக்கவும்',
      suggestionText1: 'நான் கையெழுத்திடுவதற்கு முன் என் வாடகை ஒப்பந்தத்தை மதிப்பாய்வு செய்ய முடியுமா?',
      suggestionText2: 'என் வீட்டு உரிமையாளர் பாதுகாப்பு வைப்புத்தொகையைத் திரும்பத் தர மறுக்கிறார்.',
      suggestionText3: 'பாதுகாப்பு வைப்புத்தொகை குறித்து வீட்டு உரிமையாளருக்கு சட்ட அறிவிப்பு ஒன்று தயாரிக்க வேண்டும்.',
      approvedSuffix: 'பயனரால் ஒப்புக்கொள்ளப்பட்டது',
      approvedBody: 'பயனர் பரிந்துரைக்கப்பட்ட நிபுணரை ஒப்புக்கொண்டார். சூழல் சார்ந்த கையளிப்பு தயாராகிறது...',
      deniedTitle: 'முகவர் கோரிக்கை நிராகரிக்கப்பட்டது',
      tryDifferent: 'வேறு நிபுணரை முயற்சிக்கவும்',
      responseReadySuffix: 'பதில் தயார்',
      handoffBody: 'கையளிப்பின் போது பகிரப்பட்ட சூழலை அடிப்படையாகக் கொண்டு உங்கள் நிபுணர் பதிலைத் தயார் செய்துள்ளார்.',
      errorBody: 'அந்தப் படியை முடிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      tryAgain: 'மீண்டும் முயற்சிக்கவும்',
      inputHint: 'அனுப்ப Enter · புதிய வரிக்கு Shift + Enter',
    },
    history: {
      title: 'உரையாடல் வரலாறு',
      subtitle: 'சட்ட ஆர்கெஸ்ட்ரேட்டருடன் முந்தைய உரையாடல்களை மீண்டும் பார்க்கவும்.',
      empty: 'இதுவரை உரையாடல் வரலாறு இல்லை.',
      conversation: 'உரையாடல்',
      staticDemo: 'இது ஒரு நிலையான டெமோ காட்சி — முழுமையான அமர்வுக்கு முதன்மை உரையாடல் திரையிலிருந்து மீண்டும் திறக்கவும்.',
    },
    settings: {
      title: 'அமைப்புகள்',
      subtitle: 'உங்கள் தோற்றம், மொழி மற்றும் உரையாடல் தரவை நிர்வகிக்கவும்.',
      appearance: 'தோற்றம்',
      appearanceDesc: 'உங்கள் சாதனத்தில் Legal Setu எப்படி தோன்றும் என்பதைத் தேர்வு செய்யவும்.',
      theme: 'தீம்',
      themeDesc: 'Light அல்லது Dark பயன்முறை, செயலி முழுவதும் ஒத்திசைக்கப்படும்.',
      light: 'Light',
      dark: 'Dark',
      language: 'மொழி',
      languageNote: 'இந்த டெமோவிற்கு தளம் முழுவதும் உள்ள உரை மொழிபெயர்க்கப்பட்டுள்ளது.',
      interfaceLanguage: 'இடைமுக மொழி',
      profile: 'சுயவிவரம்',
      displayName: 'காட்சிப் பெயர்',
      conversation: 'உரையாடல்',
      clearHistory: 'வரலாற்றை அழிக்கவும்',
      clearDesc: 'சேமிக்கப்பட்ட அனைத்து உரையாடல்களையும் நீக்கவும்.',
      clearedMsg: 'உரையாடல் வரலாறு அழிக்கப்பட்டது.',
      privacy: 'தனியுரிமை',
      shareData: 'பதில்களை மேம்படுத்த அநாமதேய தரவைப் பகிரவும்',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'சுயவிவரம்',
      settings: 'அமைப்புகள்',
      theme: 'தீம்',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'சட்ட ஆர்கெஸ்ட்ரேட்டர்',
      analyzing: 'உங்கள் கேள்வி ஆய்வு செய்யப்படுகிறது…',
      step1: 'நிலைமையைப் புரிந்துகொள்கிறது',
      step2: 'சட்டத் துறையை கண்டறிகிறது',
      step3: 'பொருத்தமான நிபுணத்துவத்தைத் தேர்ந்தெடுக்கிறது',
    },
    domain: {
      identifiedPrefix: 'துறை கண்டறியப்பட்டது:',
      detected: 'கண்டறியப்பட்ட துறை',
      topic: 'தலைப்பு',
      intent: 'பயனரின் நோக்கம்',
    },
    recommendation: { title: 'பரிந்துரைக்கப்பட்ட முகவர்', reason: 'காரணம்' },
    handoff: {
      handingOff: 'கையளிக்கப்படுகிறது',
      preparing: 'சூழல் சார்ந்த கையளிப்பு தயாராகிறது…',
      contextExtracted: 'சூழல் பெறப்பட்டது',
      targetAgent: 'இலக்கு முகவர்',
      working: 'செயல்படுகிறது',
      ready: 'தயார்',
      contextualHandoff: 'சூழல் சார்ந்த கையளிப்பு',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI உதவியுடன் சட்டத் தகவலை வழங்குகிறது, இது தொழில்முறை சட்ட ஆலோசனைக்கு மாற்றாக இல்லை.',
    },
    approval: { allow: 'அனுமதி', deny: 'நிராகரி' },
    home: {
      title: 'Legal Setu',
      desc: 'உங்கள் சட்டக் கேள்வியை எளிய மொழியில் கேளுங்கள். சட்ட ஆர்கெஸ்ட்ரேட்டர் சரியான துறையை கண்டறிந்து ஒரு நிபுணர் முகவரைப் பரிந்துரைக்கும் — அவரை இணைத்துக் கொள்வதா என்பதை நீங்கள் முடிவு செய்யலாம்.',
      start: 'உரையாடலைத் தொடங்கவும்',
    },
    profile: {
      title: 'சுயவிவரம்',
      desc: 'Legal Setu-இல் உங்கள் கணக்கு விவரங்கள்.',
      account: 'கணக்கு',
      fullName: 'முழுப் பெயர்',
      email: 'Email',
      signedInVia: 'இதன் மூலம் உள்நுழைந்தது',
      memberSince: 'உறுப்பினரான நாள்',
    },
    login: {
      welcome: 'Legal Setu-க்கு வரவேற்கிறோம்',
      desc: 'தனிப்பயனாக்கப்பட்ட சட்ட வழிகாட்டுதலைப் பெற உள்நுழையவும், உங்கள் உரையாடல் வரலாறு மற்றும் சூழல் உங்கள் கணக்கில் சேமிக்கப்படும்.',
      magicSentPrefix: 'Magic link அனுப்பப்பட்டது',
      magicSentSuffix: '. உங்கள் இன்பாக்ஸைப் பார்த்து, உள்நுழைய அதைக் கிளிக் செய்யவும்.',
      redirecting: 'Google-க்கு திருப்பி விடப்படுகிறது…',
      continueGoogle: 'Google மூலம் தொடரவும்',
      or: 'அல்லது',
      emailPlaceholder: 'you@example.com',
      sending: 'இணைப்பு அனுப்பப்படுகிறது…',
      sendLink: 'Magic link அனுப்பவும்',
      terms: 'தொடர்வதன் மூலம் இது ஒரு ஹாக்கத்தான் முன்மாதிரி என்றும், தொழில்முறை சட்ட ஆலோசனைக்கு மாற்றாக அல்ல என்றும் ஒப்புக்கொள்கிறீர்கள்.',
    },
  },
  te: {
    nav: { newChat: 'కొత్త చాట్', history: 'చరిత్ర' },
    chat: {
      heading: 'ఈ రోజు మీ న్యాయపరమైన ప్రశ్నకు నేను ఎలా సహాయం చేయగలను?',
      subheading: 'సరళమైన భాషలో, మీకు అనుకూలమైన భాషలో అడగండి.',
      placeholder: 'మీ న్యాయ సమస్యను వివరించండి...',
      suggestion1: 'ఒప్పందాన్ని సమీక్షించండి',
      suggestion2: 'నా అద్దెదారు హక్కులు తెలుసుకోండి',
      suggestion3: 'న్యాయ నోటీసు రూపొందించండి',
      suggestionText1: 'సంతకం చేయడానికి ముందు నా అద్దె ఒప్పందాన్ని సమీక్షించగలరా?',
      suggestionText2: 'నా ఇంటి యజమాని నా సెక్యూరిటీ డిపాజిట్ తిరిగి ఇవ్వడానికి నిరాకరిస్తున్నారు.',
      suggestionText3: 'సెక్యూరిటీ డిపాజిట్ గురించి నా ఇంటి యజమానికి న్యాయ నోటీసు రూపొందించాలి.',
      approvedSuffix: 'యూజర్ ఆమోదించారు',
      approvedBody: 'యూజర్ సూచించిన నిపుణుడిని ఆమోదించారు. సందర్భోచిత హ్యాండాఫ్ సిద్ధమవుతోంది...',
      deniedTitle: 'ఏజెంట్ అభ్యర్థన తిరస్కరించబడింది',
      tryDifferent: 'వేరే నిపుణుడిని ప్రయత్నించండి',
      responseReadySuffix: 'ప్రతిస్పందన సిద్ధంగా ఉంది',
      handoffBody: 'హ్యాండాఫ్ సమయంలో పంచుకున్న సందర్భం ఆధారంగా మీ నిపుణుడు ప్రతిస్పందనను సిద్ధం చేశారు.',
      errorBody: 'ఆ దశ పూర్తి కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
      tryAgain: 'మళ్లీ ప్రయత్నించండి',
      inputHint: 'పంపడానికి Enter · కొత్త లైన్ కోసం Shift + Enter',
    },
    history: {
      title: 'సంభాషణ చరిత్ర',
      subtitle: 'లీగల్ ఆర్కెస్ట్రేటర్‌తో గత సంభాషణలను మళ్లీ చూడండి.',
      empty: 'ఇంకా సంభాషణ చరిత్ర లేదు.',
      conversation: 'సంభాషణ',
      staticDemo: 'ఇది ఒక స్థిర డెమో వీక్షణ — పూర్తి సెషన్ కోసం ప్రధాన చాట్‌కు వెళ్లండి.',
    },
    settings: {
      title: 'సెట్టింగ్‌లు',
      subtitle: 'మీ రూపురేఖలు, భాష మరియు సంభాషణ డేటాను నిర్వహించండి.',
      appearance: 'రూపురేఖలు',
      appearanceDesc: 'లీగల్ సేతు మీ పరికరంలో ఎలా కనిపించాలో ఎంచుకోండి.',
      theme: 'థీమ్',
      themeDesc: 'లైట్ లేదా డార్క్ మోడ్, యాప్ మొత్తంలో సమన్వయమవుతుంది.',
      light: 'Light',
      dark: 'Dark',
      language: 'భాష',
      languageNote: 'ఈ డెమో కోసం సైట్ మొత్తం టెక్స్ట్ అనువదించబడింది.',
      interfaceLanguage: 'ఇంటర్‌ఫేస్ భాష',
      profile: 'Profile',
      displayName: 'ప్రదర్శన పేరు',
      conversation: 'సంభాషణ',
      clearHistory: 'చరిత్రను తొలగించండి',
      clearedMsg: 'సంభాషణ చరిత్ర తొలగించబడింది.',
      clearDesc: 'సేవ్ చేసిన అన్ని సంభాషణలను తీసివేయండి.',
      privacy: 'గోప్యత',
      shareData: 'ప్రతిస్పందనలను మెరుగుపరచడానికి అనామక డేటాను పంచుకోండి',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'లీగల్ ఆర్కెస్ట్రేటర్',
      analyzing: 'మీ ప్రశ్నను విశ్లేషిస్తోంది…',
      step1: 'పరిస్థితిని అర్థం చేసుకోవడం',
      step2: 'న్యాయ విభాగాన్ని గుర్తించడం',
      step3: 'సంబంధిత నైపుణ్యాన్ని ఎంచుకోవడం',
    },
    domain: {
      identifiedPrefix: 'విభాగం గుర్తించబడింది:',
      detected: 'గుర్తించిన విభాగం',
      topic: 'అంశం',
      intent: 'యూజర్ ఉద్దేశం',
    },
    recommendation: { title: 'సూచించిన ఏజెంట్', reason: 'కారణం' },
    handoff: {
      handingOff: 'హ్యాండాఫ్ జరుగుతోంది',
      preparing: 'సందర్భోచిత హ్యాండాఫ్ సిద్ధమవుతోంది…',
      contextExtracted: 'సందర్భం సేకరించబడింది',
      targetAgent: 'లక్ష్య ఏజెంట్',
      working: 'పని జరుగుతోంది',
      ready: 'సిద్ధం',
      contextualHandoff: 'సందర్భోచిత హ్యాండాఫ్',
    },
    agentResponse: {
      disclaimer: 'లీగల్ సేతు AI సహాయంతో న్యాయ సమాచారాన్ని అందిస్తుంది, ఇది వృత్తిపరమైన న్యాయ సలహాకు ప్రత్యామ్నాయం కాదు.',
    },
    approval: { allow: 'అనుమతించండి', deny: 'తిరస్కరించండి' },
    home: {
      title: 'Legal Setu',
      desc: 'మీ న్యాయ ప్రశ్నను సరళమైన భాషలో అడగండి. లీగల్ ఆర్కెస్ట్రేటర్ సరైన విభాగాన్ని గుర్తించి నిపుణుడైన ఏజెంట్‌ను సూచిస్తుంది — వారిని చేర్చుకోవాలా వద్దా అనేది మీరు నిర్ణయిస్తారు.',
      start: 'సంభాషణ ప్రారంభించండి',
    },
    profile: {
      title: 'Profile',
      desc: 'లీగల్ సేతులో మీ ఖాతా వివరాలు.',
      account: 'ఖాతా',
      fullName: 'పూర్తి పేరు',
      email: 'Email',
      signedInVia: 'సైన్ ఇన్ చేసిన విధానం',
      memberSince: 'సభ్యుడిగా ఉన్న తేదీ',
    },
    login: {
      welcome: 'Legal Setu కి స్వాగతం',
      desc: 'వ్యక్తిగతీకరించిన న్యాయ మార్గదర్శకత్వం కోసం సైన్ ఇన్ చేయండి, మీ సంభాషణ చరిత్ర మరియు సందర్భం మీ ఖాతాలో సేవ్ చేయబడతాయి.',
      magicSentPrefix: 'మ్యాజిక్ లింక్ పంపబడింది',
      magicSentSuffix: '. మీ ఇన్‌బాక్స్ చూసి సైన్ ఇన్ చేయడానికి దానిపై క్లిక్ చేయండి.',
      redirecting: 'Google కి రీడైరెక్ట్ అవుతోంది…',
      continueGoogle: 'Google తో కొనసాగించండి',
      or: 'లేదా',
      emailPlaceholder: 'you@example.com',
      sending: 'లింక్ పంపుతోంది…',
      sendLink: 'మ్యాజిక్ లింక్ పంపండి',
      terms: 'కొనసాగించడం ద్వారా ఇది ఒక హ్యాకథాన్ ప్రోటోటైప్ అని, వృత్తిపరమైన న్యాయ సలహాకు ప్రత్యామ్నాయం కాదని మీరు అంగీకరిస్తున్నారు.',
    },
  },
  kn: {
    nav: { newChat: 'ಹೊಸ ಸಂಭಾಷಣೆ', history: 'ಇತಿಹಾಸ' },
    chat: {
      heading: 'ಇಂದು ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಗೆ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
      subheading: 'ಸರಳ ಭಾಷೆಯಲ್ಲಿ, ನಿಮಗೆ ಅನುಕೂಲಕರವಾದ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಿ.',
      placeholder: 'ನಿಮ್ಮ ಕಾನೂನು ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...',
      suggestion1: 'ಒಂದು ಒಪ್ಪಂದವನ್ನು ಪರಿಶೀಲಿಸಿ',
      suggestion2: 'ನನ್ನ ಬಾಡಿಗೆದಾರರ ಹಕ್ಕುಗಳನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ',
      suggestion3: 'ಕಾನೂನು ನೋಟಿಸ್ ಕರಡು ಮಾಡಿ',
      suggestionText1: 'ಸಹಿ ಮಾಡುವ ಮೊದಲು ನನ್ನ ಬಾಡಿಗೆ ಒಪ್ಪಂದವನ್ನು ಪರಿಶೀಲಿಸಬಹುದೇ?',
      suggestionText2: 'ನನ್ನ ಮನೆಯ ಮಾಲೀಕರು ಭದ್ರತಾ ಠೇವಣಿಯನ್ನು ಹಿಂತಿರುಗಿಸಲು ನಿರಾಕರಿಸುತ್ತಿದ್ದಾರೆ.',
      suggestionText3: 'ಭದ್ರತಾ ಠೇವಣಿಯ ಬಗ್ಗೆ ನನ್ನ ಮನೆಯ ಮಾಲೀಕರಿಗೆ ಕಾನೂನು ನೋಟಿಸ್ ಕರಡು ಮಾಡಬೇಕು.',
      approvedSuffix: 'ಬಳಕೆದಾರರಿಂದ ಅನುಮೋದಿಸಲಾಗಿದೆ',
      approvedBody: 'ಬಳಕೆದಾರರು ಶಿಫಾರಸು ಮಾಡಿದ ತಜ್ಞರನ್ನು ಅನುಮೋದಿಸಿದ್ದಾರೆ. ಸಂದರ್ಭಾನುಸಾರ ಹಸ್ತಾಂತರ ಸಿದ್ಧವಾಗುತ್ತಿದೆ...',
      deniedTitle: 'ಏಜೆಂಟ್ ವಿನಂತಿ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
      tryDifferent: 'ಬೇರೊಬ್ಬ ತಜ್ಞರನ್ನು ಪ್ರಯತ್ನಿಸಿ',
      responseReadySuffix: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಿದ್ಧವಿದೆ',
      handoffBody: 'ಹಸ್ತಾಂತರದ ಸಮಯದಲ್ಲಿ ಹಂಚಿಕೊಂಡ ಸಂದರ್ಭದ ಆಧಾರದ ಮೇಲೆ ನಿಮ್ಮ ತಜ್ಞರು ಪ್ರತಿಕ್ರಿಯೆ ಸಿದ್ಧಪಡಿಸಿದ್ದಾರೆ.',
      errorBody: 'ಆ ಹಂತವನ್ನು ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      inputHint: 'ಕಳುಹಿಸಲು Enter · ಹೊಸ ಸಾಲಿಗೆ Shift + Enter',
    },
    history: {
      title: 'ಸಂಭಾಷಣೆಯ ಇತಿಹಾಸ',
      subtitle: 'ಲೀಗಲ್ ಆರ್ಕೆಸ್ಟ್ರೇಟರ್ ಜೊತೆಗಿನ ಹಿಂದಿನ ಸಂಭಾಷಣೆಗಳನ್ನು ಪುನಃ ವೀಕ್ಷಿಸಿ.',
      empty: 'ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆಯ ಇತಿಹಾಸವಿಲ್ಲ.',
      conversation: 'ಸಂಭಾಷಣೆ',
      staticDemo: 'ಇದು ಒಂದು ಸ್ಥಿರ ಡೆಮೊ ವೀಕ್ಷಣೆ — ಪೂರ್ಣ ಸೆಷನ್‌ಗಾಗಿ ಮುಖ್ಯ ಚಾಟ್ ಅನುಭವಕ್ಕೆ ಹೋಗಿ.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'ನಿಮ್ಮ ಗೋಚರತೆ, ಭಾಷೆ ಮತ್ತು ಸಂಭಾಷಣೆಯ ಡೇಟಾವನ್ನು ನಿರ್ವಹಿಸಿ.',
      appearance: 'ಗೋಚರತೆ',
      appearanceDesc: 'ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ Legal Setu ಹೇಗೆ ಕಾಣಿಸಬೇಕೆಂದು ಆಯ್ಕೆ ಮಾಡಿ.',
      theme: 'Theme',
      themeDesc: 'Light ಅಥವಾ Dark ಮೋಡ್, ಇಡೀ ಆ್ಯಪ್‌ನಲ್ಲಿ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
      light: 'Light',
      dark: 'Dark',
      language: 'ಭಾಷೆ',
      languageNote: 'ಈ ಡೆಮೊಗಾಗಿ ಇಡೀ ಸೈಟಿನ ಪಠ್ಯವನ್ನು ಅನುವಾದಿಸಲಾಗಿದೆ.',
      interfaceLanguage: 'ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ',
      profile: 'Profile',
      displayName: 'ಪ್ರದರ್ಶಿತ ಹೆಸರು',
      conversation: 'ಸಂಭಾಷಣೆ',
      clearHistory: 'ಇತಿಹಾಸ ಅಳಿಸಿ',
      clearedMsg: 'ಸಂಭಾಷಣೆಯ ಇತಿಹಾಸವನ್ನು ಅಳಿಸಲಾಗಿದೆ.',
      clearDesc: 'ಎಲ್ಲಾ ಉಳಿಸಿದ ಸಂಭಾಷಣೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
      privacy: 'Privacy',
      shareData: 'ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ಸುಧಾರಿಸಲು ಅನಾಮಧೇಯ ಡೇಟಾವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
      step1: 'ಪರಿಸ್ಥಿತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು',
      step2: 'ಕಾನೂನು ಕ್ಷೇತ್ರವನ್ನು ಗುರುತಿಸುವುದು',
      step3: 'ಸಂಬಂಧಿತ ಪರಿಣತಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡುವುದು',
    },
    domain: {
      identifiedPrefix: 'ಗುರುತಿಸಲಾದ ಕ್ಷೇತ್ರ:',
      detected: 'ಗುರುತಿಸಲಾದ ಕ್ಷೇತ್ರ',
      topic: 'ವಿಷಯ',
      intent: 'ಬಳಕೆದಾರರ ಉದ್ದೇಶ',
    },
    recommendation: { title: 'ಶಿಫಾರಸು ಮಾಡಿದ ಏಜೆಂಟ್', reason: 'ಕಾರಣ' },
    handoff: {
      handingOff: 'ಹಸ್ತಾಂತರಿಸಲಾಗುತ್ತಿದೆ',
      preparing: 'ಸಂದರ್ಭಾನುಸಾರ ಹಸ್ತಾಂತರ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…',
      contextExtracted: 'ಸಂದರ್ಭ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ',
      targetAgent: 'ಗುರಿ ಏಜೆಂಟ್',
      working: 'ಕೆಲಸ ನಡೆಯುತ್ತಿದೆ',
      ready: 'ಸಿದ್ಧ',
      contextualHandoff: 'ಸಂದರ್ಭಾನುಸಾರ ಹಸ್ತಾಂತರ',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-ಆಧಾರಿತ ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸುತ್ತದೆ, ಇದು ವೃತ್ತಿಪರ ಕಾನೂನು ಸಲಹೆಗೆ ಬದಲಾಗಿ ಅಲ್ಲ.',
    },
    approval: { allow: 'ಅನುಮತಿಸಿ', deny: 'ನಿರಾಕರಿಸಿ' },
    home: {
      title: 'Legal Setu',
      desc: 'ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಯನ್ನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಿ. Legal Orchestrator ಸರಿಯಾದ ಕ್ಷೇತ್ರವನ್ನು ಗುರುತಿಸಿ ತಜ್ಞ ಏಜೆಂಟ್ ಅನ್ನು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ — ಅವರನ್ನು ಸೇರಿಸಿಕೊಳ್ಳಬೇಕೆ ಎಂದು ನೀವು ನಿರ್ಧರಿಸುತ್ತೀರಿ.',
      start: 'ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu ನಲ್ಲಿ ನಿಮ್ಮ ಖಾತೆಯ ವಿವರಗಳು.',
      account: 'ಖಾತೆ',
      fullName: 'ಪೂರ್ಣ ಹೆಸರು',
      email: 'Email',
      signedInVia: 'ಇದರ ಮೂಲಕ ಸೈನ್ ಇನ್ ಆಗಿದೆ',
      memberSince: 'ಸದಸ್ಯರಾದ ದಿನಾಂಕ',
    },
    login: {
      welcome: 'Legal Setu ಗೆ ಸ್ವಾಗತ',
      desc: 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಕಾನೂನು ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ, ನಿಮ್ಮ ಸಂಭಾಷಣೆಯ ಇತಿಹಾಸ ಮತ್ತು ಸಂದರ್ಭವನ್ನು ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಉಳಿಸಲಾಗುತ್ತದೆ.',
      magicSentPrefix: 'ಮ್ಯಾಜಿಕ್ ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗಿದೆ',
      magicSentSuffix: '. ನಿಮ್ಮ ಇನ್‌ಬಾಕ್ಸ್ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್ ಮಾಡಲು ಅದನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ.',
      redirecting: 'Google ಗೆ ಮರುನಿರ್ದೇಶಿಸಲಾಗುತ್ತಿದೆ…',
      continueGoogle: 'Google ಜೊತೆ ಮುಂದುವರಿಸಿ',
      or: 'ಅಥವಾ',
      emailPlaceholder: 'neevu@example.com',
      sending: 'ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…',
      sendLink: 'ಮ್ಯಾಜಿಕ್ ಲಿಂಕ್ ಕಳುಹಿಸಿ',
      terms: 'ಮುಂದುವರಿಸುವ ಮೂಲಕ ಇದು ಒಂದು ಹ್ಯಾಕಥಾನ್ ಪ್ರೊಟೋಟೈಪ್ ಎಂದೂ, ವೃತ್ತಿಪರ ಕಾನೂನು ಸಲಹೆಗೆ ಬದಲಾಗಿ ಅಲ್ಲ ಎಂದೂ ನೀವು ಒಪ್ಪಿಕೊಳ್ಳುತ್ತೀರಿ.',
    },
  },
  gu: {
    nav: { newChat: 'નવી વાતચીત', history: 'ઇતિહાસ' },
    chat: {
      heading: 'આજે હું તમારા કાનૂની પ્રશ્નમાં કેવી રીતે મદદ કરી શકું?',
      subheading: 'સરળ ભાષામાં, તમને અનુકૂળ હોય તે ભાષામાં પૂછો.',
      placeholder: 'તમારી કાનૂની સમસ્યાનું વર્ણન કરો...',
      suggestion1: 'કરાર તપાસો',
      suggestion2: 'મારા ભાડૂત તરીકેના હકો જાણો',
      suggestion3: 'કાનૂની નોટિસનો મુસદ્દો બનાવો',
      suggestionText1: 'સહી કરતાં પહેલાં શું તમે મારો ભાડા કરાર તપાસી શકશો?',
      suggestionText2: 'મારો મકાનમાલિક મારી સિક્યુરિટી ડિપોઝિટ પાછી આપવાનો ઇનકાર કરી રહ્યો છે.',
      suggestionText3: 'સિક્યુરિટી ડિપોઝિટ બાબતે મારે મકાનમાલિકને કાનૂની નોટિસનો મુસદ્દો બનાવવો છે.',
      approvedSuffix: 'વપરાશકર્તા દ્વારા મંજૂર',
      approvedBody: 'વપરાશકર્તાએ સૂચવેલા નિષ્ણાતને મંજૂરી આપી. સંદર્ભ સાથે હેન્ડઓફ તૈયાર થઈ રહ્યું છે...',
      deniedTitle: 'એજન્ટની વિનંતી નકારવામાં આવી',
      tryDifferent: 'બીજા નિષ્ણાત અજમાવો',
      responseReadySuffix: 'જવાબ તૈયાર છે',
      handoffBody: 'તમારા નિષ્ણાતે હેન્ડઓફ દરમિયાન શેર કરેલા સંદર્ભના આધારે જવાબ તૈયાર કર્યો છે.',
      errorBody: 'આ પગલું પૂર્ણ થઈ શક્યું નથી. કૃપા કરી ફરીથી પ્રયત્ન કરો.',
      tryAgain: 'ફરીથી પ્રયત્ન કરો',
      inputHint: 'મોકલવા માટે Enter · નવી લાઇન માટે Shift + Enter',
    },
    history: {
      title: 'વાતચીતનો ઇતિહાસ',
      subtitle: 'Legal Orchestrator સાથેની જૂની વાતચીતો ફરી જુઓ.',
      empty: 'હજુ સુધી કોઈ વાતચીતનો ઇતિહાસ નથી.',
      conversation: 'વાતચીત',
      staticDemo: 'આ એક સ્થિર ડેમો દૃશ્ય છે — સંપૂર્ણ સત્ર માટે મુખ્ય ચેટ અનુભવમાંથી ફરી ખોલો.',
    },
    settings: {
      title: 'Settings',
      subtitle: 'તમારો દેખાવ, ભાષા અને વાતચીતનો ડેટા સંચાલિત કરો.',
      appearance: 'દેખાવ',
      appearanceDesc: 'તમારા ડિવાઇસ પર Legal Setu કેવો દેખાય તે પસંદ કરો.',
      theme: 'Theme',
      themeDesc: 'Light કે Dark મોડ, સમગ્ર એપમાં સિંક થાય છે.',
      light: 'Light',
      dark: 'Dark',
      language: 'ભાષા',
      languageNote: 'આ ડેમો માટે સમગ્ર સાઇટ પર ઇન્ટરફેસ ટેક્સ્ટનું ભાષાંતર કરવામાં આવ્યું છે.',
      interfaceLanguage: 'ઇન્ટરફેસ ભાષા',
      profile: 'Profile',
      displayName: 'પ્રદર્શન નામ',
      conversation: 'વાતચીત',
      clearHistory: 'ઇતિહાસ સાફ કરો',
      clearedMsg: 'વાતચીતનો ઇતિહાસ સાફ કરવામાં આવ્યો છે.',
      clearDesc: 'બધી સાચવેલી વાતચીતો દૂર કરો.',
      privacy: 'Privacy',
      shareData: 'જવાબો સુધારવા માટે અનામી ડેટા શેર કરો',
      usageAnalytics: 'Usage analytics',
    },
    userMenu: {
      profile: 'Profile',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      signOut: 'Sign out',
    },
    orchestrator: {
      title: 'Legal Orchestrator',
      analyzing: 'તમારો પ્રશ્ન વિશ્લેષણ કરવામાં આવી રહ્યો છે…',
      step1: 'પરિસ્થિતિ સમજવી',
      step2: 'કાનૂની ક્ષેત્ર ઓળખવું',
      step3: 'સંબંધિત નિપુણતા પસંદ કરવી',
    },
    domain: {
      identifiedPrefix: 'ક્ષેત્ર ઓળખાયું:',
      detected: 'ઓળખાયેલું ક્ષેત્ર',
      topic: 'વિષય',
      intent: 'વપરાશકર્તાનો હેતુ',
    },
    recommendation: { title: 'સૂચવેલ એજન્ટ', reason: 'કારણ' },
    handoff: {
      handingOff: 'હેન્ડઓફ થઈ રહ્યું છે',
      preparing: 'સંદર્ભ સાથે હેન્ડઓફ તૈયાર થઈ રહ્યું છે…',
      contextExtracted: 'સંદર્ભ કાઢવામાં આવ્યો',
      targetAgent: 'લક્ષ્ય એજન્ટ',
      working: 'કામ ચાલુ છે',
      ready: 'તૈયાર',
      contextualHandoff: 'સંદર્ભાત્મક હેન્ડઓફ',
    },
    agentResponse: {
      disclaimer: 'Legal Setu AI-સહાયિત કાનૂની માહિતી પૂરી પાડે છે અને વ્યાવસાયિક કાનૂની સલાહનો વિકલ્પ નથી.',
    },
    approval: { allow: 'મંજૂર કરો', deny: 'નકારો' },
    home: {
      title: 'Legal Setu',
      desc: 'તમારો કાનૂની પ્રશ્ન સરળ ભાષામાં પૂછો. Legal Orchestrator યોગ્ય ક્ષેત્ર ઓળખીને નિષ્ણાત એજન્ટ સૂચવે છે — તેમને સામેલ કરવા કે નહીં તે તમે નક્કી કરો છો.',
      start: 'વાતચીત શરૂ કરો',
    },
    profile: {
      title: 'Profile',
      desc: 'Legal Setu પર તમારા ખાતાની વિગતો.',
      account: 'Account',
      fullName: 'પૂરું નામ',
      email: 'Email',
      signedInVia: 'આના દ્વારા સાઇન ઇન કર્યું',
      memberSince: 'સભ્ય બન્યાની તારીખ',
    },
    login: {
      welcome: 'Legal Setu માં તમારું સ્વાગત છે',
      desc: 'વ્યક્તિગત કાનૂની માર્ગદર્શન મેળવવા સાઇન ઇન કરો, તમારી વાતચીતનો ઇતિહાસ અને સંદર્ભ તમારા ખાતામાં સચવાયેલા રહેશે.',
      magicSentPrefix: 'મેજિક લિંક મોકલવામાં આવી',
      magicSentSuffix: '. તમારું ઇનબોક્સ તપાસો અને સાઇન ઇન કરવા માટે તેના પર ક્લિક કરો.',
      redirecting: 'Google પર રીડાયરેક્ટ થઈ રહ્યું છે…',
      continueGoogle: 'Google સાથે ચાલુ રાખો',
      or: 'અથવા',
      emailPlaceholder: 'you@example.com',
      sending: 'લિંક મોકલવામાં આવી રહી છે…',
      sendLink: 'મેજિક લિંક મોકલો',
      terms: 'ચાલુ રાખીને તમે સંમત થાઓ છો કે આ એક હેકાથોન પ્રોટોટાઇપ છે, વ્યાવસાયિક કાનૂની સલાહનો વિકલ્પ નથી.',
    },
  },
  ur: {
    nav: { newChat: 'نئی گفتگو' },
    chat: {
      heading: 'آج میں آپ کے قانونی سوال میں کیسے مدد کر سکتا ہوں؟',
      subheading: 'سادہ زبان میں، اس زبان میں پوچھیں جس میں آپ آسانی محسوس کرتے ہیں۔',
      placeholder: 'اپنا قانونی مسئلہ بیان کریں...',
    },
  },
  or: {
    nav: { newChat: 'ନୂଆ ଚାଟ୍' },
    chat: {
      heading: 'ଆଜି ମୁଁ ଆପଣଙ୍କ ଆଇନଗତ ପ୍ରଶ୍ନରେ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
      subheading: 'ସରଳ ଭାଷାରେ, ଆପଣ ସହଜ ଅନୁଭବ କରୁଥିବା ଭାଷାରେ ପଚାରନ୍ତୁ।',
      placeholder: 'ଆପଣଙ୍କ ଆଇନଗତ ସମସ୍ୟା ବର୍ଣ୍ଣନା କରନ୍ତୁ...',
    },
  },
  pa: {
    nav: { newChat: 'ਨਵੀਂ ਗੱਲਬਾਤ' },
    chat: {
      heading: 'ਅੱਜ ਮੈਂ ਤੁਹਾਡੇ ਕਾਨੂੰਨੀ ਸਵਾਲ ਵਿੱਚ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?',
      subheading: 'ਸਾਦੀ ਭਾਸ਼ਾ ਵਿੱਚ, ਜਿਸ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਸੀਂ ਸਹਿਜ ਹੋ, ਪੁੱਛੋ।',
      placeholder: 'ਆਪਣੀ ਕਾਨੂੰਨੀ ਸਮੱਸਿਆ ਦੱਸੋ...',
    },
  },
  ml: {
    nav: { newChat: 'പുതിയ ചാറ്റ്' },
    chat: {
      heading: 'ഇന്ന് നിങ്ങളുടെ നിയമപരമായ ചോദ്യത്തിൽ ഞാൻ എങ്ങനെ സഹായിക്കാം?',
      subheading: 'ലളിതമായ ഭാഷയിൽ, നിങ്ങൾക്ക് സൗകര്യപ്രദമായ ഭാഷയിൽ ചോദിക്കുക.',
      placeholder: 'നിങ്ങളുടെ നിയമപ്രശ്നം വിവരിക്കുക...',
    },
  },
  as: {
    nav: { newChat: 'নতুন আলাপ' },
    chat: {
      heading: 'আজি মই আপোনাৰ আইনী প্ৰশ্নত কেনেকৈ সহায় কৰিব পাৰোঁ?',
      subheading: 'সহজ ভাষাত, আপুনি সহজ অনুভৱ কৰা ভাষাত সোধক।',
      placeholder: 'আপোনাৰ আইনী সমস্যা বৰ্ণনা কৰক...',
    },
  },
  mai: {
    nav: { newChat: 'नव बातचीत' },
    chat: {
      heading: 'आइ हम अहाँक कानूनी प्रश्नमे कोना मदद क सकैत छी?',
      subheading: 'सरल भाषामे, जे भाषामे अहाँ सहज होई से पूछू।',
      placeholder: 'अपन कानूनी समस्या वर्णन करू...',
    },
  },
  sa: {
    nav: { newChat: 'नूतनं संभाषणम्' },
    chat: {
      heading: 'अद्य अहं भवतः विधिविषयकं प्रश्नं कथं साहाय्यं कर्तुं शक्नोमि?',
      subheading: 'सरलभाषायां, या भाषा भवते सुगमा तस्यां पृच्छतु।',
      placeholder: 'स्वकीयां विधिसमस्यां वर्णयतु...',
    },
  },
  ks: {
    nav: { newChat: 'नव गुफ्तगू' },
    chat: {
      heading: 'आज़ मैं तोहनिस कानूनी सवालस मंज़ किताह मदद करी हेकां?',
      subheading: 'आसान ज़बानि मंज़, यि ज़बान तोहय आसान लगान, तिमी पुछिव।',
      placeholder: 'पनुन कानूनी मसला बयान करिव...',
    },
  },
  ne: {
    nav: { newChat: 'नयाँ कुराकानी' },
    chat: {
      heading: 'आज म तपाईंको कानूनी प्रश्नमा कसरी मद्दत गर्न सक्छु?',
      subheading: 'सरल भाषामा, तपाईंलाई सहज लाग्ने भाषामा सोध्नुहोस्।',
      placeholder: 'तपाईंको कानूनी समस्या वर्णन गर्नुहोस्...',
    },
  },
  kok: {
    nav: { newChat: 'नवें संभाषण' },
    chat: {
      heading: 'आज हांव तुमच्या कायदेशीर प्रस्नांत कशी मदत करूं येता?',
      subheading: 'सोप्या भाशेंत, तुमकां सुविधायेची भास वापरून विचारात.',
      placeholder: 'तुमची कायदेशीर समस्या वर्णन करात...',
    },
  },
  sd: {
    nav: { newChat: 'نئين ڳالهه ٻولهه' },
    chat: {
      heading: 'اڄ مان توهانجي قانوني سوال ۾ ڪيئن مدد ڪري سگهان ٿو؟',
      subheading: 'سولي ٻولي ۾، جيڪا ٻولي توهان کي آسان لڳي تنهن ۾ پڇو.',
      placeholder: 'پنهنجي قانوني مسئلي جو بيان ڪريو...',
    },
  },
  doi: {
    nav: { newChat: 'नमीं गल्लबात' },
    chat: {
      heading: 'अज्ज मैं तुंदे कानूनी सवाल च कि मदद करी सकनै?',
      subheading: 'सोखी भाशा च, जिस भाशा च तुसें आसान लगदा पुच्छो।',
      placeholder: 'आपणी कानूनी समस्या दस्सो...',
    },
  },
  mni: {
    nav: { newChat: 'ꯋꯥꯔꯤ ꯑꯅꯧꯕ' },
    chat: {
      heading: 'ꯉꯁꯤ ꯑꯩꯅ ꯅꯪꯒꯤ ꯋꯥꯌꯦꯜ ꯑꯁꯤꯗ ꯀꯔꯝꯅ ꯃꯇꯦꯡ ꯄꯥꯡꯒꯅꯤ?',
      subheading: 'ꯄꯥꯡꯒꯜ ꯂꯣꯟꯗ, ꯅꯪꯅ ꯆꯪꯅ ꯉꯝꯅꯕ ꯂꯣꯟꯗ ꯍꯪꯕꯤꯌꯨ.',
      placeholder: 'ꯅꯪꯒꯤ ꯋꯥꯌꯦꯜ ꯋꯥꯐꯝ ꯍꯥꯢꯕꯤꯌꯨ...',
    },
  },
  sat: {
    nav: { newChat: 'नावा रोड़ो' },
    chat: {
      heading: 'तिंगिन आम आम रेयाक़ आइनी प्रोस्नो रे चेत लेकान मदद दाड़ेयाम?',
      subheading: 'सोलोमोन पारसिक ते, जाहान पारसिक आमाक़ सोलोमोन लागोआ ओना ते कुली मे.',
      placeholder: 'आमाक़ आइनी गोंडेय ओलाओ मे...',
    },
  },
  brx: {
    nav: { newChat: 'गोदान सल्लाहनाय' },
    chat: {
      heading: 'दिनै आं नोंथाङा कानूनी प्रश्नाव मोन्दिनि दा गोहो होनो हागौ?',
      subheading: 'सुबुं फोरमानि रावजों, नोंथाङा गोहो जागायथारि रावजों सुंगोन।',
      placeholder: 'नोंथाङनि कानूनी समस्याखौ फोरमायदों...',
    },
  },
};

export function AppProvider({ children }) {
  const { user } = useAuth();
  const [language, setLanguage] = useState('en');
  const [historyCleared, setHistoryCleared] = useState(false);
  const [displayName, setDisplayName] = useState('');
  const [nameEdited, setNameEdited] = useState(false);

  // Default the display name from the signed-in account until the user
  // edits it themselves in Settings.
  useEffect(() => {
    if (nameEdited) return;
    const fallback = user?.user_metadata?.full_name || user?.email?.split('@')[0] || '';
    setDisplayName(fallback);
  }, [user, nameEdited]);

  const updateDisplayName = useCallback((name) => {
    setNameEdited(true);
    setDisplayName(name);
  }, []);

  const t = useCallback(
    (key) => {
      const path = key.split('.');
      const lookup = (dict) => path.reduce((acc, part) => (acc == null ? acc : acc[part]), dict);
      return lookup(STRINGS[language]) ?? lookup(STRINGS.en) ?? key;
    },
    [language]
  );

  const clearHistory = useCallback(() => setHistoryCleared(true), []);

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        t,
        historyCleared,
        clearHistory,
        displayName,
        setDisplayName: updateDisplayName,
      }}
    >
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}
