import { Link } from 'react-router-dom';
import LegalIcon from '../components/LegalIcon.jsx';

export default function TermsOfService() {
  return (
    <div className="page-wrap legal-doc">
      <Link to="/" className="legal-back-link">
        &larr; Back to Legal Setu
      </Link>

      <h1 className="page-title">Terms of Service</h1>
      <p className="legal-meta">Last updated: 23 August 2026</p>

      <p>
        These Terms of Service govern your use of Legal Setu, a prototype AI legal-assistance
        tool built by team &ldquo;sudo rm -rf last_braincell&rdquo; for All India Hackathon 2026
        (Problem Statement PS-013). By creating an account or using Legal Setu, you agree to
        these Terms and to our <Link to="/privacy">Privacy Policy</Link>.
      </p>

      <div className="legal-callout">
        <span className="legal-callout-icon">
          <LegalIcon name="alertTriangle" size={18} strokeWidth={2} />
        </span>
        <p>
          Legal Setu is not a law firm and does not provide legal advice. Responses are generated
          by AI agents for informational and educational purposes only, may be incomplete or
          incorrect, and do not create an attorney-client relationship. Always confirm anything
          important with a qualified advocate before you rely on it or act on it, especially for
          time-sensitive matters (filing deadlines, court dates, notice periods).
        </p>
      </div>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 18 years old, or using Legal Setu under the supervision of a
        parent/guardian, to create an account. You&rsquo;re responsible for ensuring your use of
        Legal Setu complies with applicable law in your jurisdiction.
      </p>

      <h2>2. What Legal Setu does</h2>
      <p>
        Legal Setu&rsquo;s Legal Orchestrator reads your plain-language legal question and routes
        it to one or more of 8 specialized AI agents (query explanation, legal research, rights
        identification, case guidance, document drafting, complaint &amp; filing guidance,
        contract review, and safety flagging). Responses may draw on retrieval-augmented
        generation (RAG) grounded in sources such as the Indian Constitution and other public
        legal materials. Legal Setu is a prototype under active development; features,
        availability, and accuracy may change without notice.
      </p>

      <h2>3. Not legal advice</h2>
      <p>
        Using Legal Setu does not make you a client of any lawyer or law firm, and no agent,
        response, or document generated by Legal Setu should be treated as a substitute for
        advice from a licensed advocate who knows the specifics of your situation. Document
        drafts (notices, RTIs, affidavits, etc.) generated by Legal Setu are starting points only
        and must be reviewed before use.
      </p>

      <h2>4. Your account</h2>
      <p>
        You&rsquo;re responsible for maintaining the confidentiality of your login credentials and
        for all activity under your account. Notify us promptly at legalsetu.team@gmail.com if
        you suspect unauthorized access. We use Supabase to manage authentication, including
        optional Google sign-in.
      </p>

      <h2>5. Acceptable use</h2>
      <ul>
        <li>Using Legal Setu for illegal purposes or to facilitate illegal activity.</li>
        <li>Submitting content that is abusive, defamatory, or infringes others&rsquo; rights.</li>
        <li>Attempting to reverse-engineer, scrape, or overload the service.</li>
        <li>Misrepresenting your identity.</li>
        <li>
          Relying on Legal Setu as a replacement for licensed legal representation in matters
          where that is required by law (e.g. court appearances).
        </li>
      </ul>

      <h2>6. Your content</h2>
      <p>
        You retain ownership of the questions, documents, and other content you submit
        (&ldquo;your content&rdquo;). By submitting it, you grant Legal Setu a limited license to
        process, store, and use your content to operate and improve the service, as described in
        our Privacy Policy. Don&rsquo;t submit content you don&rsquo;t have the right to share, or
        sensitive identifiers (Aadhaar, PAN, financial details) you wouldn&rsquo;t want stored.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        Legal Setu&rsquo;s name, logo, orchestrator design, agent architecture, and underlying
        code are the property of team sudo rm -rf last_braincell (or their respective licensors)
        and may not be copied or reused without permission, except as allowed by the project&rsquo;s
        open-source license, if any is published in the repository.
      </p>

      <h2>8. Third-party services</h2>
      <p>
        Legal Setu relies on third-party infrastructure including Supabase, Lyzr.ai, and
        (potentially) Wolfram. Their availability and terms may affect Legal Setu&rsquo;s
        functionality; we are not responsible for outages or issues originating from these
        providers.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        Legal Setu is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
        warranties of any kind, express or implied, including accuracy, completeness, or fitness
        for a particular purpose. As a hackathon prototype, it may contain bugs, incomplete
        features, or inaccurate outputs.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, team sudo rm -rf last_braincell and Legal Setu
        will not be liable for any indirect, incidental, or consequential damages, or for any
        loss arising from reliance on AI-generated content, arising out of your use of Legal
        Setu.
      </p>

      <h2>11. Termination</h2>
      <p>
        You may stop using Legal Setu and delete your account at any time from Settings. We may
        suspend or terminate access if we reasonably believe these Terms have been violated.
      </p>

      <h2>12. Governing law</h2>
      <p>
        These Terms are governed by the laws of India, and any disputes will be subject to the
        exclusive jurisdiction of the courts of India.
      </p>

      <h2>13. Changes to these terms</h2>
      <p>
        We may update these Terms at any time, at our sole discretion, without prior notice to
        you. The &ldquo;Last updated&rdquo; date above reflects the most recent revision.
        Continued use of Legal Setu after changes take effect means you accept the updated Terms.
      </p>

      <h2>14. Contact</h2>
      <p>Questions about these Terms: legalsetu.team@gmail.com.</p>

      <div className="legal-doc-footer">
        <Link to="/privacy">Read our Privacy Policy &rarr;</Link>
      </div>
    </div>
  );
}
